### ISSUE TITLE
Scopes defined on Abstract ActiveRecord classes are missing table names when called from subclasses

### ISSUE THREAD

**Issue by lsylvester** [rails/rails#10658]
If a scope is defined on an abstract active record class, when it is called by one of its subclasses the sql generated is missing a table name.

```ruby 
class AbstractCompany < ActiveRecord::Base
  self.abstract_class = true
  
  scope :abstract_company_scope, ->{ order('id') }
end

class Company < AbstractCompany
end

Company.abstract_company_scope #=> ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: : SELECT  "".* FROM ""   ORDER BY id LIMIT 1
```

Test has been added at lsylvester/rails@c64023bc9fd7dfe10f564fedbd7299240bd5da15

**Comment by mrbrdo** [comment]
Can someone look into this?

**Comment by gjastrab** [comment]
Yes having this problem as well.  We have an abstract base class with some included model concerns in it that many of our other core models inherit from.  Scopes defined in those model concerns are having this problem.  Does #10862 not correct it?

**Comment by sgrif** [comment]
This should be fixed on master. Can someone confirm?

**Comment by lsylvester** [comment]
I can confirm that this is now working correctly on master.

**Comment by saulius** [comment]
Still seems to be broken in `4-2-stable`. Here you can find a failing test case in https://github.com/lsylvester/rails/commit/c64023bc9fd7dfe10f564fedbd7299240bd5da15 from (https://github.com/rails/rails/pull/10862).

**Comment by mmontossi** [comment]
This is still broken on rails 4.2.4?

Test case: https://gist.github.com/mmontossi/b6aa5718b21eb8e43e9c

**Comment by denispeplin** [comment]
I can confirm that it's broken in Rails 4.2.4

**Comment by mmontossi** [comment]
@denispeplin you can try pull the branch fix_10658 from my rails repo, it's the exact rails repo with just the fix for this issue, I tried to submit the pull request to fix this on rails 4 but was considered too risky to touch those parts rails on a stable branch. So we probably won't probably see this fixed until rails 5.

**Comment by swrobel** [comment]
@sgrif @lsylvester do you know which commit resolved this issue on master? I can't seem to find it.

**Comment by yivo** [comment]
Not fixed in Rails 4.2.7.1
