### ISSUE TITLE
.unscope modifies source relation if it hasn't been executed / sqled yet

### ISSUE THREAD

**Issue by universal** [rails/rails#17738]
I noticed some unexpected behavior using rewhere / unscope today. If one calls rewhere/unscope on a relation which hasn't been executed / converted to sql yet, it changes the source relation. I created a dummy app to reproduce the problem: https://github.com/universal/unscopeTest.

The relevant unit test is the following:
```ruby
require 'test_helper'

class UserTest < ActiveSupport::TestCase
  test "unscope doesn't change source query" do
    a = User.where(email: "foo")
    b = a.unscope(where: :email)
    # this assertion fails
    assert a.to_sql != b.to_sql, "#{a.to_sql} should not be #{b.to_sql}"
  end

  test "unscope doesn't change executed source query" do
    a = User.where(email: "foo")
    a.load
    b = a.unscope(where: :email)
    # this assertion works
    assert a.to_sql != b.to_sql, "#{a.to_sql} should not be #{b.to_sql}"
  end

  test "unscope doesn't change sql'ed source query" do
    a = User.where(email: "foo")
    a.to_sql
    b = a.unscope(where: :email)
    # this assertion works
    assert a.to_sql != b.to_sql, "#{a.to_sql} should not be #{b.to_sql}"
  end

  test "where conditions are not shared" do
    a = User.where(email: "name")
    b = a.unscope(where: :email)
    # this assertion fails
    assert a.where_values.object_id != b.where_values.object_id, "where values of relations should not be shared"
  end
end
```

The behavior seems to occur at least in Rails 4.1.2 to 4.1.8. I haven't tested the 4.2.beta.

**Comment by tobypinder** [comment]
I'm 99% sure I'm still experiencing this on 4.2.0.

**Comment by sgrif** [comment]
This has been resolved on master, and I will backport for 4.2.1

**Comment by tobypinder** [comment]
Is this still going to make the backport? As of 4.2.1rc3 I'm still seeing the mutative "bang" version of reject.

https://github.com/rails/rails/blob/v4.2.1.rc3/activerecord/lib/active_record/relation/query_methods.rb#L907

**Comment by bquorning** [comment]
It looks like the mentioned fix on master was in c80487eb1ae7f35cc780745b4f951a79e1a3482b and ae8cd56c7b1f3130eb3b8f2632a528a8fc78e56c. I cannot see that this has been backported to other branches.

**Comment by tobypinder** [comment]
Is the fix for this specifically targeting Rails 5? We see that the implementation has changed in the master branch, but `4-2-stable` and tag `v4.2.1.rc4` still mutates using `reject!`, corrupting the ActiveRecord state as @workmad3 suggested in https://github.com/rails/rails/issues/17738#issuecomment-64211134

**Comment by mintuhouse** [comment]
I have tried to add the following file to my initializers (trying to monkey patch the method in rails 4.1.10)
````
Rails.application.config.to_prepare do
  ActiveRecord::QueryMethods::WhereChain.class_eval do
    def where_unscoping(target_value)
      puts "Loading from initializer ..."
      target_value = target_value.to_s

      self.where_values = where_values.reject do |rel| #MODIFIED
        case rel
        when Arel::Nodes::In, Arel::Nodes::NotIn, Arel::Nodes::Equality, Arel::Nodes::NotEqual
          subrelation = (rel.left.kind_of?(Arel::Attributes::Attribute) ? rel.left : rel.right)
          subrelation.name.to_s == target_value
        end
      end

      self.bind_values = bind_values.reject { |col,_| col.name == target_value }
    end
  end
end
````
But I still see that the unscope is still modifying the original relation.

Is there a change that this will get ported to rails 4.1 or a patch I can apply to fix the issue?

**Comment by tobypinder** [comment]
@mintuhouse The monkeypatch was working for us... Are you certain that it's being applied properly? We compiled our own version of the rails gem internally with just those changes and had no problems.

I'd like to see it in 4.1 but given current movement it looks like we may have to wait for 5.

**Comment by tobypinder** [comment]
This is fixed in #20722 21e05a0
