### ISSUE TITLE
Regression - scope of a relation is applied to unrelated object

### ISSUE THREAD

**Issue by phallguy** [rails/rails#19882]
This appears to be an issue with current_scope caching at the class level. When a where condition uses a subquery, the current scope is merged into the subquery producing incorrect results.

Note, this was previously submitted as #19804 but incorrectly closed. This is a breaking change from previously working code in v3.x that is now broken due to caching introduced in the 4.x line.

Test cases

``` ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'rack', github: 'rack/rack'
    gem 'i18n', github: 'svenfuchs/i18n'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:campaigns) do |t|
    t.string :name
  end

  create_table(:participants) do |t|
    t.integer :priority
    t.references :campaign
    t.references :user
  end

  create_table(:users) do |t|
    t.string :name
  end
end


class Campaign < ActiveRecord::Base
  has_many :participants, inverse_of: :resource
end

class Participant < ActiveRecord::Base
  belongs_to :user, inverse_of: :participants
  belongs_to :campaign, inverse_of: :participants

  # @!attribute priority
  # @return [Integer] some arbitrary column to filter by.

  scope :in_campaigns, ->( campaigns ) {
    campaigns = campaigns.select( :id )
    where( campaign_id: campaigns )
  }

  scope :with_priority, ->( priority ) {
    where( priority: priority )
  }
end

class User < ActiveRecord::Base
  has_many :participants, inverse_of: :user
  has_many :campaigns, through: :participants
end


class BugTest < Minitest::Test

  def setup
    @john  = User.create! name: "John"
    @jane  = User.create! name: "Jane"

    book  = Campaign.create! name: "Book"
    shoe  = Campaign.create! name: "Shoe"


    @john.participants.create campaign: book, priority: 1

    @jane.participants.create campaign: shoe, priority: 1
    @jane.participants.create campaign: book, priority: 5
  end

  def test_includes_intersection_when_filter_preceeds_join
    participants = Participant.with_priority 1
    participants = participants.in_campaigns( @jane.campaigns )

    assert participants.size == 2
  end

  def test_includes_intersection_when_filter_succeeds_join
    participants = Participant.in_campaigns( @jane.campaigns )
    participants = participants.with_priority 1

    assert participants.size == 2
  end

end
```

Both tests should produce the same result. The order however becomes significant because the precondition `with_priority 1` is applied to `jane.campaigns`  in which there is only one participant in that campaign.

You can observe the incorrect behavior by examining the SQL itself. In both cases, the SQL generated should be

``` sql
SELECT COUNT(*)
FROM "participants"
WHERE "participants"."campaign_id" IN
    (SELECT "campaigns"."id"
     FROM "campaigns"
     INNER JOIN "participants" ON "campaigns"."id" = "participants"."campaign_id"
     WHERE "participants"."user_id" = ?)
  AND "participants"."priority" = ? 

[["user_id", 4], ["priority", 1]]
```

Notice that priority is only applied once. In the failing test however, priority is applied twice:

``` sql
SELECT COUNT(*)
FROM "participants"
WHERE "participants"."priority" = ?
  AND "participants"."campaign_id" IN
    (SELECT "campaigns"."id"
     FROM "campaigns"
     INNER JOIN "participants" ON "campaigns"."id" = "participants"."campaign_id"
     WHERE "participants"."priority" = ?
       AND "participants"."user_id" = ?) 

[["priority", 1], ["priority", 1], ["user_id", 2]]
```

I've done some initial debugging and it seems to be related to the #scoping call using #current_scope when merging the in_campaigns scope, but #current_scope is overwritten to include the priority constraint wen the in_campaigns scope is resolved, and that applies an additional unwanted constraint.

**Comment by matthewd** [comment]
> This is a breaking change from previously working code in v3.x that is now broken due to caching introduced in the 4.x line.

Another way of phrasing that would be "I want this to work as it did in 3.x, and as it has not done for the last 2 years". Which is clearly a breaking change from all supported versions. While that might've been a tenable argument 18 months ago, "restoring it wouldn't be a breaking change" is, at this point, patently false: if it's a breaking change from the historical behaviour, then restoring that historical behaviour would be a breaking change from the current behaviour.

(Yes, that's a perfectly normal thing to do if we've just accidentally broken compatibility, but you're proposing that we break compatibility with the entirety of the last three release series. That's... not the same thing.)

To further colour @sgrif's [comment](https://github.com/rails/rails/issues/19804#issuecomment-94174218) with my own opinion: the current behaviour sucks. It's unintuitive, difficult to properly work around, and generally error-prone.

But again, it's worked that way for some time now.

I'd love to see it change for 5.0, though. That's where we run into the larger hurdle: it doesn't work like that because someone thought it'd be a good idea: it is, as I understand it, a fairly deep consequence of the implementation. Please do investigate; patches very welcome.

I'm not going to close this, because you'll presumably just open yet another issue -- hopefully someone from core can give you a sufficiently definitive response.

**Comment by phallguy** [comment]
I'm not sure I understand the desire and defense of incorrect behavior. Certainly this is unintended behavior in the current release and those that depend on the behavior are expecting ActiveRecord/Arel to perform _incorrectly_ and return unexpected results. 

I've also confirmed that it _used_ to work in version 4.1.10 as well. It worked as recently as March 19, 2105.  This is a _recent breaking change_ to the way active record and arel deal with caching.

**Comment by phallguy** [comment]
Hmm, may have been a bit ambitious on the 4.1 working. But the statement about incorrect behavior still stands.

**Comment by rafaelfranca** [comment]
If it breaks at Rails 4.0 we can't call recent. Rails 4 us already 3 years
old and I'd say that the majority of users are using this release series,
if we change the behavior to match Rails 3 we may break every single
application running with rails 4. If that is the case we can't fix on the
Rails 4 release series even if it is wrong. Rails 5 is another history.

**Comment by pixeltrix** [comment]
> Rails 5 is another history

I hope it's a future :smile:

**Comment by matthewd** [comment]
For reference, I found the older report: #14003. (Which would've been much easier if I'd remembered it was assigned to me :flushed:)

**Comment by phallguy** [comment]
I think the argument that it worked in rails 3 and not in 4 is really irrelevant. It doesn't really matter if it worked in 3.x, it's incorrect behavior and should be fixed for current and future release.

Dealing with set logic, A | B should equal B | A. It used to be implemented correctly. Currently depending on the order in which the AST is built, rails generates SQL as either A | B or incorrectly as A | ( B & A ). Even if this broke a long time ago, it is incorrect behavior and I believe it should be fixed.

**Comment by rafaelfranca** [comment]
> it is incorrect behavior and I believe it should be fixed.

:+1: I think we all agree on that

**Comment by PikachuEXE** [comment]
This has been an issue for a long time.
I workaround with using a scope which always use a certain order of scopes:
```ruby
def scope_a
# ...
end
def scope_b
# ...
end
def scope_a_and_b
# avoiding bug ...
end
```
But it's really painful debugging before I know it's a rails bug and worked around

**Comment by PikachuEXE** [comment]
@phallguy Can you still reproduce this issue on 4.1/4.2/master?

**Comment by phallguy** [comment]
Yes the problem still persists. 4.2.3 in fact is even worse and has even more cases where the order in which the relations are scoped leaks state into the global context and breaks the resulting query. Unfortunately while the caching added by adequate record provides a welcome speed improvement, it introduces many failing edge cases due to it's dependence on global state.

**Comment by kamipo** [comment]
This haven't happened since 5.0.6 and 5.1.4.
