### ISSUE TITLE
constant auto loading causes Module#const_get(name, false) to load and return the requested name from ancestors (violating const_get spec)

### ISSUE THREAD

**Issue by bughit** [rails/rails#26030]
I don't have a test case yet, but would like to know if this is a known limitation of auto loading.  Breaking the ruby api should be avoided if possible, which it may be in this case.

const_get could be overridden setting a ivar flag for the duration of the call (if the second argument is false) which would inform const_missing to avoid searching ancestors.

**Comment by bughit** [comment]
an example class hierarchy

```
root
  Class1
  Module1
    Class1
```
so you're calling `Module1.const_get('Class1', false)` and getting `::Class1`

**Comment by bughit** [comment]
>  the proposed solution, for example, is insufficient because a const_get can cause an arbitrary amount of code to be executed, outside our control.

What is the evidence for this?  const_get behavior is well defined, AFAICT it will either return the loaded constant, or call const_missing.

If so, overriding const_get can reliably inform (via an `ensure` cleared ivar) the subsequent const_missing (if any) on the same stack to avoid walking inheritance chain.

Rails should not be breaking Ruby if it can avoid it.

**Comment by bughit** [comment]
@fxn - I am curious what you think, can this be reliably fixed using the proposed method

**Comment by matthewd** [comment]
> What is the evidence for this?

http://ruby-doc.org/core-2.3.1/Module.html#method-i-autoload

(It could also hit someone else's `const_missing`.)

**Comment by bughit** [comment]
> (It could also hit someone else's const_missing.)

I take it you're referring to something like this:

```ruby
class Module
	def const_missing(*args)
		puts 'Module#const_missing'
	end
end

module M1
	def self.const_missing(*args)
		p 'M1::const_missing', args
		super
	end
end

M1.const_get(:C1)
```

If there is a const_missing invocation before the Rails' one, it will either return the constant (case closed) or eventually end up calling the Rails's one via super.  So if the Rails' const_missing is called that way, while const_get is still on the stack (const_get is saving the signal to const_missing in an ivar of the receiver module, ivar named after the module being requested), the fix can still be applied.  So why is that insufficient?

**Comment by pixeltrix** [comment]
@bughit I'm not sure what breaking of Ruby's API that you're seeing, I created this:

``` ruby
# app/models/foo.rb
class Foo; end

# app/models/bar.rb
module Bar; end

# app/models/bar/foo.rb
class Foo; module Bar; end; end
```

and then tested the following scenarios:

``` irb
# No constants loaded
>> Bar.const_get(:Foo, false)
=> Bar::Foo

# ::Foo loaded
>> Bar.const_get(:Foo, false)
=> Bar::Foo

# ::Foo and ::Bar::Foo loaded
>> Bar.const_get(:Foo, false)
=> Bar::Foo
```

The only discrepancy I see is when nested constant isn't loaded and you ask `const_get` to search ancestors. e.g:

``` irb
# No constants loaded
>> Bar.const_get(:Foo, true)
=> Bar::Foo

# ::Foo loaded
>> Bar.const_get(:Foo, true)
=> Foo

# ::Foo and ::Bar::Foo loaded
>> Bar.const_get(:Foo, true)
=> Bar::Foo
```

You could argue that `Object` isn't in the ancestors of the `Bar` module and so it shouldn't be found but that doesn't match your description. Can you clarify please.

**Comment by bughit** [comment]
corrected example: Class1 is actually not in Module1, which is what causes autoloading to kick in

an example class hierarchy

```
root
  Class1
  Module1
    Class2
```
so you're calling `Module1.const_get('Class1', false)` and getting `::Class1`

**Comment by bughit** [comment]
@pixeltrix did that clarify it?

**Comment by fxn** [comment]
@bughit about to take a flight.

Could you please use standard notation defining classes and modules with Ruby? We have nesting, inheritance, and "root" is Object (no need to make it explicit).

**Comment by bughit** [comment]
@fxn 

sure, to clarify further, the hierarchy shown is a nesting one, not inheritance, Class1 and Module1 are in top level (i.e. Object) and CLass2 is nested in Module1

**Comment by fxn** [comment]
But could you please just provide a minimal Ruby snippet? Otherwise we have to make hypothesis whose validity we do not know and that difficults reasoning. If you provide Ruby code then all is clear about the examples.

**Comment by bughit** [comment]
I tested this in a new Rails5 project

```ruby
# app/models/class1.rb
class Class1
end

#app/models/module1/class2.rb
module Module1
  class Class2
  end
end
```

`Module1.const_get(:Class1, false)` in production console produces a NameError as expected, but returns `::Class1` in development console

**Comment by bughit** [comment]
previous mentions of autoloading ancestor search should be saying the nesting hierarchy search, since that's what load_missing_constant actually searches.

**Comment by bughit** [comment]
The second arg (false) to const_get is only necessary to repro because Object is visited by both the const_get ancestor search and load_missing_constant nesting search

But if we make the nesting deeper and remove this intersection in Object, you can repro also without the false arg

```ruby
# app/models/module1/class1.rb
module Module1
  class Class1
  end
end


#app/models/module1/module2/class2.rb
module Module1
  module Module2
    class Class2
    end
  end
end
```

`Module1::Module2.const_get(:Class1)` in production console produces a NameError as expected, but returns `::Module1::Class1` in development console

**Comment by bogdanvlviv** [comment]
Last example of code in my development console works correctly. I haven't saw issue.

**Comment by bughit** [comment]
Here's what I'm getting

```
Loading development environment (Rails 5.0.0)
irb(main):001:0> Module1::Module2.const_get(:Class1)
=> Module1::Class1
irb(main):002:0> Module1::Module2.const_get(:Class1)
NameError: uninitialized constant Module1::Module2::Class1
```

So it returns the class (incorrectly) the first time.  I think the following comment from  load_missing_constant explains this:

```
        # If our parents do not have a constant named +const_name+ then we are free
        # to attempt to load upwards. If they do have such a constant, then this
        # const_missing must be due to from_mod::const_name, which should not
        # return constants from from_mod's parents.
```

**Comment by bogdanvlviv** [comment]
http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-algorithms-qualified-references

**Comment by bughit** [comment]
This bug is about const_get, not constant identifiers in code. 

First you said you could not repro, now you can?

**Comment by pixeltrix** [comment]
@bughit yes, changing from `Class1` to `Class2` clarifies things for me. Does the same issue apply when using classes for nesting instead of modules?

**Comment by fxn** [comment]
@bughit In Rails, constant autoloading does *not* check ancestors. Passing `false` and not passing `false` is the same as far as dependencies.rb is concerned.

Constant autoloading only checks the "namespaces". That is, autoloading a constant called "C" from a class or module object whose `name` method returns "A::B" makes Rails look for the files _a/b/c.rb_ and _a/b/c_. That is all. If `A::B` has ancestors, Rails ignores them.

The problem is that `const_missing` is not passed the nesting. So, in the previous example Rails assumes the nesting is `[A::B, A]`. It is an assumption, which doesn't hold in `A::B::C`, but it is all we can do because Ruby does not pass this context.

What we can do is to document and explain the gotcha, that is covered in http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#nesting-and-qualified-constants.

**Comment by bughit** [comment]
@fxn 

I've already corrected the initial confusion over ancestor searching.  It is const_get that searches ancestors while load_missing_constant looks at Module#parent.

The part you did not address is the proposed fix:  since in this case, the `const_missing(<NAME>)` call is in response to a `const_get(<NAME>)` which is currently on the stack, there actually is enough information to avoid the Module#parent search.

The existing code is clearly trying to support the const_get scenario, here's the comment:

```
        # If our parents do not have a constant named +const_name+ then we are free
        # to attempt to load upwards. If they do have such a constant, then this
        # const_missing must be due to from_mod::const_name, which should not
        # return constants from from_mod's parents.
```

but failing, hence this bug. The solution I proposed is pretty simple, overriding const_get:

not tested
```ruby
# module prepended to Module
def const_get(name, *)
  const_get_signal_ivar = "___const_get_#{name}_is_on_the stack__"
  instance_variable_set const_get_signal_ivar, true
  super
ensure
  remove instance_variable const_get_signal_ivar
end
```
Then load_missing_constant can check for the presence of this ivar, and avoid looking at Module#parent

What is wrong with this fix that it should be rejected leave const_get broken in development?

**Comment by bughit** [comment]
@pixeltrix I haven't tried classes, does rails support folders that represent classes rather than modules?

**Comment by bughit** [comment]
There may be a threading issue with using a module instances ivar, but I think it can be addressed with PerThreadRegistry or something similar to ensure a different var per pthread

**Comment by bughit** [comment]
here's the fix that's thread safe

```ruby
 
    # Module prepends this
    module ModuleConstGet
      def const_get(const_name, *)
        if signal_const_get = !anonymous? && self != Object
          const_get_signal_var = "calling_#{name}_const_get_#{const_name}"
          Thread.current[const_get_signal_var] = true
        end
        super
      ensure
        Thread.current[const_get_signal_var] = nil if signal_const_get
      end
    end

      # in ModuleConstMissing
      def const_missing(const_name)
        const_get_signal_var = "calling_#{name}_const_get_#{const_name}"
        look_in_parent = !Thread.current.key?(const_get_signal_var)
        from_mod = anonymous? ? guess_for_anonymous(const_name) : self
        Dependencies.load_missing_constant(from_mod, const_name, look_in_parent: look_in_parent)
      end
```

load_missing_constant takes an extra param, look_at parent defaulting to true

```ruby
def load_missing_constant(from_mod, const_name, look_in_parent: true)
```

and only goes to the parent when it's true

```ruby
      elsif look_in_parent && (parent = from_mod.parent) && parent != from_mod &&
            ! from_mod.parents.any? { |p| p.const_defined?(const_name, false) }

```

**Comment by bughit** [comment]
I tested the above on rails master and it does eliminate the problem

**Comment by bughit** [comment]
since String#constantize uses const_get it also has this problem
`'Module1::Module2::Class1'.constantize` loads `Module1::Class1`

**Comment by fxn** [comment]
Hey, need to find the time to reply.

`constantize` does what it does, and loading that class is expected.

Rails autoliading does not attempt nor does it claim to follow Ruby rules. On the contrary, it is a feature with its contract and does not follow Ruby rules.

Autoloading is a feature whose behaviour is documented in the guide. You have to approach it positively: "it works this way", rather than by comparing it to an ideal that does not follow.

We'd like it not to be this way, but we see no way as of today to reimplement it in a way that fully matches Ruby.

The `const_get` gotcha... need to think about it.

**Comment by pixeltrix** [comment]
> I haven't tried classes, does rails support folders that represent classes rather than modules?

@bughit yes, for example you can have the following:

``` ruby
# app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

# app/models/product/category.rb
class Product < ActiveRecord::Base
  class Category < ActiveRecord::Base
    has_many :products
  end
end
```

I often do this to namespace my tables automatically - `products` and `product_categories`.

**Comment by bughit** [comment]
@fxn

I am not trying to make auto loading perfect.   I accept its limitations that can't be addressed due to lack of information in const_missing.  These limitations pertain mostly to constant identifiers in code.  Let's set those aside.

Instead, I am highlighting a very specific breakage of const_get, which appears to be fixable.  And provided the fix actually works and does not introduce any regressions, it should not be rejected, because breaking core Ruby API should be avoided when possible.

Being able to dynamically check for existence of classes in a certain namespace, with some sort of fallback, if they are not present, is a useful pattern, which in dev mode needs a bug free const_get (const_defined? can't work in dev).

I can do a pull request for this for further evaluation.  Can this be reopened?

**Comment by bughit** [comment]
@fxn 
You asked me to clarify terms and post code.  I did all that.  So you could evaluate the fix.  There is no coherent explanation here as to why it should be rejected, leaving const_get broken in dev.

**Comment by fxn** [comment]
@bughit I told you I would think about it, and I'll do. But I didn't give you a date, give me a break man!

That said, I joined the thread because you asked for my opinion. But the issue was closed by Matthew and he gave a valid rationale I wholly respect. Please if you want to discuss, which is fine, from on try to convince him.

**Comment by bughit** [comment]
@fxn

ok, it seemed like after a week there would not be a response

> he gave a valid rationale I wholly respect

this was the rationale:

> the proposed solution, for example, is insufficient because a const_get can cause an arbitrary amount of code to be executed, outside our control

I think I addressed this,
https://github.com/rails/rails/issues/26030#issuecomment-237110835

to which there was no response.  Is that not the end of any convincing?

If you understand why the fix is invalid, per his rationale, please explain it to me, perhaps a snippet of code that will illustrate the problem.

**Comment by fxn** [comment]
I am in holidays with my family, don't expect an answer any time soon. If you believe the issue should be reopened, as I said, please convince Matthew.

**Comment by bughit** [comment]
> I didn't give you a date
> give me a break man!
> don't expect an answer any time soon.

I did not know about your holiday and did not seek to interrupt it, it's almost like you're assuming the opposite.

**Comment by matthewd** [comment]
@bughit you asked for "evidence"; I replied with a URL, and then you responded only to my parenthetical aside. 

> const_get is saving the signal to const_missing in an ivar of the receiver module, ivar named after the module being requested

This is sounding awfully complicated, to address one narrow situation in the middle of a bunch of other unsolvable ambiguities. And it's still not sufficient: the other `const_get` implementation can contain arbitrary code, so it may attempt to resolve this same constant directly (not using const_get), which would cause `const_missing` to incorrectly be invoked in "const_get mode".

I'm not going to write a snippet of code to show a bug in a loosely-described algorithm. If you wish to continue arguing that this is a solvable problem, yes please do go ahead and present actual code. Then we can evaluate whether it moves the needle enough on compatibility to justify its complexity... but be aware that *is* a factor: Rails autoloading interferes with Ruby's constant resolution rules in a multitude of ways, so there is a limit to how much code we're going to spend addressing just one. I continue to doubt that this will meet that bar, even if it can be achieved without introducing new caveats.

**Comment by bughit** [comment]
> I replied with a URL

A link to `Module#autoload` by itself does not constitute an explanation.  Autoloading via `Module#autoload` bypasses const_missing altogether, so does not affect the proposed fix nor is affected by it.  If you are claiming otherwise you'll need to explain.

> This is sounding awfully complicated,

```ruby
      def const_get(const_name, *)
        if !anonymous? && self != Object
          const_get_signal_var = "calling_#{name}_const_get_#{const_name}"
          Thread.current[const_get_signal_var] = true
        end
        super
      ensure
        Thread.current[const_get_signal_var] = nil if const_get_signal_var
      end
```

This is awfully complicated?  There is way more complicated stuff in Rails. 

> to address one narrow situation

It's not narrow, const_get is broken.  If it can return the wrong value, it can not be relied on.  Breaking a major ruby api should not be dismissed as "one narrow situation"

> in the middle of a bunch of other unsolvable ambiguities.

This is the nirvana fallacy.  If autoloading can't be made perfect let's not bother with fixing const_get?

> I'm not going to write a snippet of code to show a bug in a loosely-described algorithm. If you wish to continue arguing that this is a solvable problem, yes please do go ahead and present actual code.

I already have (https://github.com/rails/rails/issues/26030#issuecomment-237759365)   Are you looking for a pull-request?

**Comment by bughit** [comment]
pull request #26164

**Comment by bughit** [comment]
@matthewd

> I'm not going to write a snippet of code to show a bug in a loosely-described algorithm. If you wish to continue arguing that this is a solvable problem, yes please do go ahead and present actual code. Then we can evaluate whether it moves the needle enough on compatibility to justify its complexity

code has been presented a week before you wrote that (https://github.com/rails/rails/issues/26030#issuecomment-237759365), it has also been in a pull request since Sunday.
