### ISSUE TITLE
Including ActionView::Rendering in API controller without jbuilder breaks render :json

### ISSUE THREAD

**Issue by jpettettphaxio** [rails/rails#27211]
Including `ActionView::Rendering` in a controller of an API-only application breaks `render :json`, resulting in an `ActionView::MissingTemplate` error.  This is similar to #25183, except that the error occurs **without** using jbuilder.

### Steps to reproduce

1. Use `rails new --api` to create a Rails app with jbuilder disabled by default.
2. Include `ActionView::Rendering` in a controller subclassed from `ActionController::API`, then `render :json`:

```
class TestController < ActionController::API
  include ActionView::Rendering

  def index
    render json: {page: "Home"}
  end
end
```

[Full example failing test](https://gist.github.com/jpettettphaxio/303edc3639c0b0820a2fff40bf3b70e3
)

### Expected behavior
JSON response should be returned without error.  No template should be used.

### Actual behavior
`ActionView::MissingTemplate` is raised.

### System configuration
**Rails version**: 5.0.0.1 (used `rails new --api`)

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
@jpettettphaxio I just want to confirm, you are only including `ActionView::Rendering` because you want access to the controller's `view_context`, right?

**Comment by maclover7** [comment]
I believe the reason why this is throwing an error is because even though you only want `view_context`, when you include `ActionView::Rendering`, the `render_to_body` method gets overwritten and will direct the request through Action View's rendering system.

**Comment by jpettettphaxio** [comment]
@maclover7 I believe that's correct.  The reason I want to include `ActionView::Rendering` is to enable to enable Draper to work, which uses `view_context`.  However, I'm not 100% sure if that's the only method it needs.  But since the problem occurs regardless of whether Draper is used, is there a documented reason why `ActionView::Rendering` can't/shouldn't be included in `ActionController::API` or is this a Rails bug?

**Comment by jpettettphaxio** [comment]
And/or since `ActionContolller::Base` includes `ActionView::Rendering` without breaking `render :json`, is there another module that needs to be included in a `ActionController::API` subclass to "fix" `render_to_body` after including `ActionView::Rendering`?

**Comment by st0012** [comment]
@jpettettphaxio 
The cause of this error is that `ActionView::Rendering` override `render_to_body` to
```ruby
    def render_to_body(options = {})
      _process_options(options)
      _render_template(options)
    end
```

The overwrote method is `ActionController::Renderers#render_to_body`
```ruby
    def render_to_body(options)
      _render_to_body_with_renderer(options) || super
    end
```

However, re-include `ActionController::Renderers` won't work. But if you manually override `render_to_body` in your controller will work, which would be like

```ruby
class TestController < ActionController::API

  private

  def render_to_body(options)
    _render_to_body_with_renderer(options) || super
  end
end
```

**Comment by jpettettphaxio** [comment]
@st1002 thanks for looking into this.  Any reason not to simply do:

```ruby
alias_method :_orig_render_to_body, :render_to_body
include ActionView::Rendering
alias_method :render_to_body, :_orig_render_to_body
```

**Comment by st0012** [comment]
@jpettettphaxio If your approach works, just use it 😬

**Comment by NaixSpirit** [comment]
thanks @jpettettphaxio , it works, but is there another method or a pull request to fix it? 
I don't think the `alias_method` is a perfect solution 😬

**Comment by jpettettphaxio** [comment]
@NaixSpirit this work-around is no longer necessary with the latest release of Draper.

**Comment by rhymes** [comment]
I've add the same issue with Rails 5.0.4 and jbuilder 2.7.0. I have a hybrid web/API app.

I wanted to switch my API controllers from inheriting from `ActionController::Base` to `ActionController::API`

- first issue I had was that Jbuilder was rendering empty bodies like mentioned in here https://github.com/rails/jbuilder/issues/346
- I then added the following like it's suggested in a comment and elsewhere: https://github.com/rails/jbuilder/issues/346#issuecomment-270545570

```ruby
    class APIController < ActionController::API
      include ActionView::Rendering
    end
```
This unfortunately triggered a different issue with `render json: {}` that seems to ask for an obviously non existent template.

I thought this had been fixed by https://github.com/rails/rails/pull/24178 but apparently not.

The temporary solutions were either https://github.com/rails/rails/issues/27211#issuecomment-264392054 or https://github.com/rails/rails/issues/27211#issuecomment-264966302

**Comment by silva96** [comment]
Sorry I'm late, Happy birthday to this issue!. Still happening on rails 5.1

**Comment by franzliedke** [comment]
I have this issue, too.

The `draper` gem requires a view context to be available (thus manually includes `ActionView::Rendering` when Rails is in API mode), and the `responders` gem checks for the presence of `ActionView::Rendering` to determine whether it should use API or default behavior for returning a response.

As far as I can tell, `ActionView::Rendering` is not included in API mode so that the view layer is skipped (it's not needed), so this should stay that way. Having the `view_context` (and thus certain helpers, right?) available in API mode probably makes sense, though.

If I am thinking this through correctly, would this be a proper solution then?
* Split `ActionView::Rendering` into two modules, one providing the view context, and the other one taking care of rendering with the view stack.
* `ActionController::Base` would include both.
* `ActionController::API` would only include the former.

**Comment by mikkelwf** [comment]
Still an issue, rails 5.2...

**Comment by pedrofurtado** [comment]
The hack provided by @jpettettphaxio is valid until a Rails official solution. @rafaelfranca @maclover7 The suggestion of @franzliedke is mine too, the best approach is split the module 🤝

**Comment by joallard** [comment]
The reason I got here is that I have an API-only app, "except that one time I want to render HTML and JSON". So without Draper.

Here's how I got there:

1. I'm aware I didn't opt in the view system. I will make my HTML manually.
2. Strings are escaped automatically, which breaks my HTML (insert comments on dull knives here)
3. See the Rendering guide, `helpers.tag` is mentioned
4. It needs `ActionView::Rendering`
5. JSON format is now broken

Redefining `render_to_body` seems to work. (https://github.com/rails/rails/issues/27211#issuecomment-264392054)

Other option, I was willing to add something to my `render json: {}` invocation, but I'm never much able to dig into `render` as its a bit dark and deep.

**Comment by krakowski** [comment]
Hi,

this is still happening with Rails 7. Was the suggested solution (splitting the module) ever implemented?

After removing the `jbuilder` gem from my project and adding `include ActionView::Rendering` to my controller, I get an `ActionView::MissingTemplate` error.

**Comment by jcbances6** [comment]
The hack provided by @jpettettphaxio is valid, I am using rails 7.0.8, ruby 3.2.2, and gem jbuilder

add `include ActionView::Rendering`

and

```
  def render_to_body(options)
    _render_to_body_with_renderer(options) || super
  end
```
