### ISSUE TITLE
Image_tag() not producing fingerprint

### ISSUE THREAD

**Issue by yoshie902a** [rails/rails#27673]
### Steps to reproduce
Please see the posts from different people. I experience the same issues...

Post 1
http://stackoverflow.com/questions/41625778/image-tag-missing-md5-fingerprint-rails
Post 2
http://stackoverflow.com/questions/31494402/rails-4-2-image-path-and-fingerprint-only-added-when-config-assets-compile-tr

### Expected behavior
image_tag() should be producing a fingerprint for the image.

### Actual behavior
image_tag() is not producing an md5 fingerprint.

### System configuration
Rails 4.2
Ruby 2.3.1 /2.3.3

**Comment by coreyward** [comment]
I'm not experiencing the same with Rails 4.2.6 and Ruby 2.3.0 on Heroku. Can you create a minimal viable example of this behavior?

Out of curiosity, do you have `serve_static_assets` enabled in production or the [`rails_12factor`](https://github.com/heroku/rails_12factor) gem installed?

**Comment by yoshie902a** [comment]
##Server
Puma '3.6.1'

## GemFile
ruby "2.3.1"
'rails', '4.2.5'
'rails_12factor'
'heroku-deflater'

##Production
  config.serve_static_files = true || ENV['RAILS_SERVE_STATIC_FILES'].present?
  config.assets.js_compressor = :uglifier
  config.assets.compile = false 
  config.assets.digest = true

Is `serve_static_assets`  the same as `serve_static_files` above?

**Comment by coreyward** [comment]
Does the issue occur without `heroku-deflator`?

**Comment by yoshie902a** [comment]
yes

**Comment by yoshie902a** [comment]
minimal viable example:
https://github.com/yoshie902a/irc_app

**Comment by yoshie902a** [comment]
The answer was in the file names.

`image.jpeg` needed to be changed to `image.jpg`

The manifest file creates `.jpg` files, so by having `.jpeg` files, it never finds it and can not make the fingerprint.

This seems like a bug that should be fixed.

**Comment by matrix9180** [comment]
I helped @yoshie902a track this down. Afterwards I found these related tickets: 
- rails/sprockets-rails#304
- rails/sprockets-rails#246

**Comment by maclover7** [comment]
Hmm, this seems like an issue with sprockets / sprockets-rails than an issue with Rails. Can you open up an issue at the rails/sprockets repository?

**Comment by maclover7** [comment]
cc @schneems

**Comment by matrix9180** [comment]
There is also rails/sprocket-rails#42, which was closed but last comment there indicates issue wasn't resolved.

**Comment by rafaelfranca** [comment]
Closed as duplicate of https://github.com/rails/sprockets-rails/issues/304

**Comment by aivils** [comment]
After long lasting debugging I added some lines in the config/staging.rb

```ruby
  config.after_initialize do
    config.assets.debug = false
  end
```

Cannot reproduce on localhost under staging env. Only staging host is affected.

**Comment by jwigal** [comment]
One thing I just ran into that I though might be related to this (but it wasn't)... was seeing issues with non-fingerprinted image tags in emails generated. Some of my background tasks generate emails from processes that run on a database server. I use Capistrano for deployment, and it was not configured to compile assets on the database server. Since Rails didn't see a corresponding asset on the database server, it didn't provide a fingerprinted URL when the email was generated.
