### ISSUE TITLE
Time Zone tests fail on Windows

### ISSUE THREAD

**Issue by wagenet** [rails/rails#28463]
With Ruby 2.3.3 on Windows on the v5.1.0-beta1 tag two time zone related tests fail.

```
$ rake test TEST=test/core_ext/duration_test.rb
C:/Ruby23-x64/bin/ruby.exe -w -I"lib;test" -I"C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib" "C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/core_ext/duration_test.rb"
Run options: --seed 40946

# Running:

.....................F...............F..

Finished in 0.180922s, 221.0900 runs/s, 1116.5045 assertions/s.

  1) Failure:
DurationTest#test_adding_hours_across_dst_boundary [E:/rails/activesupport/test/core_ext/duration_test.rb:184]:
Expected: 2009-03-30 00:00:00 +0000
  Actual: 2009-03-30 01:00:00 +0000


  2) Failure:
DurationTest#test_since_and_ago_anchored_to_time_zone_now_when_time_zone_is_set [E:/rails/activesupport/test/core_ext/duration_test.rb:170]:
Expected: 2000-01-01 00:00:05 UTC
  Actual: 1999-12-31 19:00:05 UTC

40 runs, 202 assertions, 2 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib;test" -I"C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib" "C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/core_ext/duration_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

On 32-bit Ruby, there's also the additional failure:

```
  1) Error:
DurationTest#test_iso8601_output_and_reparsing:
ArgumentError: invalid date
    E:/rails/activesupport/lib/active_support/core_ext/date/calculations.rb:113:in `>>'
    E:/rails/activesupport/lib/active_support/core_ext/date/calculations.rb:113:in `advance'
    E:/rails/activesupport/lib/active_support/core_ext/time/calculations.rb:142:in `advance'
    E:/rails/activesupport/lib/active_support/duration.rb:227:in `block in sum'
    E:/rails/activesupport/lib/active_support/duration.rb:218:in `each'
    E:/rails/activesupport/lib/active_support/duration.rb:218:in `inject'
    E:/rails/activesupport/lib/active_support/duration.rb:218:in `sum'
    E:/rails/activesupport/lib/active_support/duration.rb:180:in `since'
    E:/rails/activesupport/lib/active_support/core_ext/time/calculations.rb:232:in `plus_with_duration'
    E:/rails/activesupport/test/core_ext/duration_test.rb:345:in `block in test_iso8601_output_and_reparsing'
    E:/rails/activesupport/test/core_ext/duration_test.rb:343:in `each'
    E:/rails/activesupport/test/core_ext/duration_test.rb:343:in `test_iso8601_output_and_reparsing'
```

**Comment by maclover7** [comment]
cc @pixeltrix

**Comment by sngeth** [comment]
I was able to reproduce it.

It looks like it might be related to Windows being unable to read the ENV["TZ"] variable correctly mentioned here: https://www.ruby-forum.com/topic/68570

Assuming your windows application environment correctly sets the timezone, ActiveSupport `#ago` and `#since` should be working fine(haven't verified it though) in real world usage...  

Since the tests are manually switching timezones for testing purposes I believe these failed tests would just be false positives.

**Comment by voxik** [comment]
The "DurationTest#test_iso8601_output_and_reparsing" is old bug. I initially reported it as #25682 and it is still an issue. The test failed just today in Fedora CI:

https://apps.fedoraproject.org/koschei/package/rubygem-activesupport?collection=f27
https://kojipkgs.fedoraproject.org/work/tasks/4884/20484884/build.log

**Comment by voxik** [comment]
Still valid I am afraid ...
