### ISSUE TITLE
Validation run twice in association if parent updated since rails 5.1

### ISSUE THREAD

**Issue by kaluznyo** [rails/rails#29032]
I have an relation between order and order lines. Order has many OrderLine

In OrderLine I have one validation  where I save the order

```
validate: :check

def check
  puts 'Check'
  self.order.update_attributes!(check: true)
end
```

In rails 5.0 this scenario work fine.

```
order = Order.create 

order_line = order.lines.new(quantity: 1 , price: 10)
order_line.save
```

It create Order, update the check attributes, in once time

Since Rails 5.1 it pass to the validate, then on the line` self.order.update_attributes!(check: true)`, this produce a new pass in validate.
So this code print 'Check' twice.

For information, this code work on rails 5 and 5.1, the change is passing order as attribute or new OrderLine
```
order = Order.create 
order_line = OrderLine.new(quantity: 1 , price: 10, order: order)
order_line.save
```

I don't see anything in release log, but maybe is in...

**Comment by kaluznyo** [comment]
I get a script to see change behavior between rails 5.0.2 and 5.1.0. I add two test, One with create sub ressource with post.comments.new and one with Comment.new(post: post). Two pass on rails 5, and one fail on rails 5.1.
 Maybe my original code work because a bug that's fixed in rails 5.1, but I don't understand the difference between two way to do this 

https://gist.github.com/kaluznyo/2582e565eb6520fe8478eb878533eac5

**Comment by alexcameron89** [comment]
This behavior was added in c7adc610f0233b9afd51a6d68aa9061cdb250fad.

**Comment by p8** [comment]
This seems to be fixed on main.
The following script has green tests:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :orders do |t|
    t.boolean :check
  end

  create_table :order_lines do |t|
    t.integer :order_id
    t.integer :quantity
    t.integer :price
  end
end

class Order < ActiveRecord::Base
end

class OrderLine < ActiveRecord::Base
  attr_accessor :check_count
  belongs_to :order
  validate :check

  def check
    self.check_count ||= 0
    self.check_count += 1
    self.order.update!(check: true)
  end
end

class BugTest < Minitest::Test
  def test_has_many_through_proc
    order = Order.create
    order_line = OrderLine.new(quantity: 1 , price: 10, order: order)
    order_line.save
    assert_equal order_line.check_count, 1
  end
end
```

**Comment by alexcameron89** [comment]
@p8  I think the issue is with creating `order_lines` through the order:

```ruby
    order = Order.create
    order_line = order.order_lines.new(quantity: 1 , price: 10)
    order_line.save
    assert_equal order_line.check_count, 1 # shows 3 check_counts
```

With this script, it fails:
```ruby
begin
  gem 'bundler', '~> 1.0'
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '5.0.2'
  #gem 'rails', github: 'rails/rails', branch: "main"
  gem 'sqlite3', '~> 1.3.6'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :orders do |t|
    t.boolean :check
  end

  create_table :order_lines do |t|
    t.integer :order_id
    t.integer :quantity
    t.integer :price
  end
end

class Order < ActiveRecord::Base
  has_many :order_lines
end

class OrderLine < ActiveRecord::Base
  attr_accessor :check_count
  belongs_to :order
  validate :check

  def check
    self.check_count ||= 0
    self.check_count += 1
    self.order.update!(check: true)
  end
end

class BugTest < Minitest::Test
  def test_has_many_through_proc
    order = Order.create

    order_line = order.order_lines.new(quantity: 1 , price: 10)
    order_line.save
    assert_equal order_line.check_count, 1
  end
end
```

But, as you can see in the script, I tried it with version 5.0.2 where the author says it's supposed to pass, and it still fails. Given that the original script no longer exists as a gist and neither of us can recreate the original issue, I'm going to close it.

If the error continues to be an issue and we can reproduce it, then we can re-open it.
