### ISSUE TITLE
The behavior of `attribute_changed?` inside of after callbacks will be changing

### ISSUE THREAD

**Issue by pelcasandra** [rails/rails#29035]
I just upgraded a project to Rails 5.1.0 and I'm seeing this deprecation warning. 

    DEPRECATION WARNING: The behavior of `attribute_changed?` 
    inside of after callbacks will be changing in the next version of Rails.
    The new return value will reflect the behavior of calling the method 
    after `save` returned (e.g. the opposite of what it returns now). 
    To maintain the current behavior, use `saved_change_to_attribute?` instead. 

My code looks like this

    class MyClass
      before_valiadtion :my_method

      def my_method
        if name_changed?
          ...
        end
      end
    end

I do not understand exactly the deprecation warning. If I use `saved_change_to_name` instead it will check it after it is saved but this is before validation callback. 

I also noticed that if I change the `name_changed?` to `saved_change_to_name` my specs are not passing. 

I'm having a hard time understanding what the appropriate way to this should be. It seems to me that how it was before it was doing the job okay, not fully understand the reason behind this change and how I should avoid these deprecation warnings.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by m1neral** [comment]
According this comment https://github.com/rails/rails/pull/25337#issuecomment-225166796 `attribute_changed?` should be replaced to `will_save_change_to_attribute?` ?

Why in the `DEPRECATION WARNING` is irrelevant information?

**Comment by dinatih** [comment]
@m1neral  
> Why in the DEPRECATION WARNING is irrelevant information?

The message says to use `saved_change_to_attribute?` in place of your `will_save_change_to_attribute?` (thank you, btw) that is correct when the `attribute_changed?` is called in an `after_validation` (not an `after_save`) callback, in my case. 


```
The behavior of `attribute_changed?` inside of after callbacks will be changing in 
the next version of Rails. The new return value will reflect the behavior of calling 
the method after `save` returned (e.g. the opposite of what it returns now). 
To maintain the current behavior, use **`saved_change_to_attribute?`** instead.
```

**Comment by trezona-lecomte** [comment]
I have just encountered this same issue, and do not believe it to be a matter for support as @matthewd stated. These are the facts:

- We call `attribute_changed?` in a `before_validation`, not in any after callbacks.
- The deprecation warning triggers, advising us to not to use `attribute_changed?` in after callbacks

How is this correct or sensible behaviour?

Further, the documentation for the (apparently) [equivalent method](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Dirty.html#method-i-will_save_change_to_attribute-3F) of `attribute_changed?` in this context (i.e. not in an after callback) says simply:
```
Alias for attribute_changed?
```
This seems to be false.  `will_save_change_to_attribute?`is not defined as an alias of any other method, and has provably different behaviour from `attribute_changed?`, e.g.:
```
(byebug) foo_changed?
true
(byebug) will_save_change_to_attribute?(:foo)
nil
(byebug) saved_change_to_attribute?(:account_type)
true
```
This is within the context of a `before_validation`. 

How do we go about getting this issue re-opened? Or should I raise a new issue?

Thanks for your help.

**Comment by bborn** [comment]
+1 I agree - this notice is showing up for me even when I'm using an `attribute_changed?` method in an before_save callback. So in that case, changing it to `will_save_change_to_attribute?` as suggested by the deprecation notice will break my code.

**Comment by trezona-lecomte** [comment]
Note that the documentation discrepancy was addressed in https://github.com/rails/rails/pull/32835.

@bborn check whether you have some `after` callbacks that are causing your `before` callbacks to evaluate - in that context you will get the deprecation warning even though from reading your code it looks like you're only using the deprecated methods within `before` callbacks.

**Comment by joemsak** [comment]
@trezona-lecomte I've checked my callbacks and anything in after_* callbacks has been carefully coded to use update methods which skip callbacks, and my "*_changed?" calls are only in 1before_validation` or in `validates` conditionals and I'm still getting this error, and it's pointing to the line of code that is part of the before_validation line

**Comment by joemsak** [comment]
In the end I changed the callbacks not to check if things changed since they will do the correct behavior either way

**Comment by ccelestial** [comment]
I've done an upgrade to Rails 5.1.6 and have the same DEPRECATION warnings. If ever anyone still wants to solve this warning. Here are the steps I took:

1. Search all of your` *_changed?`.

Changed this:
```
  if name_changed?
  ...
  if user_id_changed?
```
To this if it is inside `after_*` (after_save, after_commit, after_update, after_create) blocks:
```
  if saved_change_to_name?
  ...
  if saved_change_to_user_id?
```
OR to this if it is inside `before_*` (before_save, before_commit, before_update, before_create) blocks:
```
  if will_save_change_to_name?
  ...
  if will_save_change_to_user_id?
```

On my own opinion, this is quite tricky thing to change since we've been used to `attribute_changed?`. But change is good. The syntax also made more sense now.

**Comment by ccelestial** [comment]
I've done an upgrade to Rails 5.1.6 and have the same DEPRECATION warnings. If ever anyone still wants to solve this warning. Here are the steps I took:

1. Search all of your` *_changed?`.

Changed this:
```
  if name_changed?
  ...
  if user_id_changed?
```
To this if it is inside `after_*` (after_save, after_commit, after_update, after_create) blocks:
```
  if saved_change_to_name?
  ...
  if saved_change_to_user_id?
```

On my own opinion, this is quite tricky thing to change since we've been used to `attribute_changed?`. But change is good. The syntax also made more sense now.

**Comment by joemsak** [comment]
Thank you @ccelestial I will try this advice next time I run into it, and I agree the updated syntax makes a lot of sense but I think it's fair to say the change has been difficult to work around, especially when we get these warnings in `before_*` callbacks, not just after ones, and that warning makes no mention of these new `will_save_change_to_*` methods
