### ISSUE TITLE
Credentials are wiped out on edit

### ISSUE THREAD

**Issue by aledalgrande** [rails/rails#31409]
### Steps to reproduce

1. Create a new Rails project
2. `rails credentials:edit`
3. Add new credential anywhere in the file
4. Save and exit from the editor
5. `rails credentials:show` will show what you just added

### Expected behavior

`rails credentials:edit`, when the editor opens, I see all my added credentials.

### Actual behavior

`rails credentials:edit`, when the editor opens, my added credentials are gone.

The message is always:
```
New credentials encrypted and saved.
```

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**Comment by crigor** [comment]
This bug is fixed on master. #31287

**Comment by y-yagi** [comment]
As crigor said, this problem has already been fixed by #31287.  
Please wait for the next version release. Thanks!

**Comment by GeorgeDonald** [comment]
in 5.2.1.1 this problem is still there.

**Comment by akukaracza82** [comment]
I have this problem i 6.0.3 Oo

**Comment by Smaily1** [comment]
Im in 5.2.8 the last 5 versions and still have the same problem

**Comment by Smaily1** [comment]
actiually I found the problem with the code editor when I use VSC it opens new empty file each time I try to edit the credentials , but using the default one which is VIM it opens the existing one so I can edit and save , I don't know why ?
