### ISSUE TITLE
6.0.0.beta2: .connected_to() block throws "No connection pool with 'primary' found."

### ISSUE THREAD

**Issue by sidot3291** [rails/rails#35800]
### Steps to reproduce
I have several databases holding the same models.  On a per-request basis, I use an `around_action` and `ActiveRecord::Base.connected_to` to make sure I'm connecting to the right database.

That around_action is implemented as:
```
ActiveRecord::Base.connected_to(database: {writing: current_instance.database_key}) do 
  yield
end
```

### Expected behavior
I would expect connections to each database to be kept alive, and my around_action switches the connection that's used for that request.

### Actual behavior
Usually with no more than 25 refreshes - all with current_instance.database_key returning the same symbol - the first query inside my action will throw "No connection pool with 'primary' found."  I know it's the first query because the first query does appear in my logs, like it would on a successful request.

### Debugging so far
I've added logs above the block to determine the current process, current thread, and connection_pool.stat.  Those look like:

```
[726575e0-5624-4f88-9a45-2eb52c4b6d52] {:size=>5, :connections=>1, :busy=>1, :dead=>0, :idle=>0, :waiting=>0, :checkout_timeout=>5}
[726575e0-5624-4f88-9a45-2eb52c4b6d52] Process 61 Thread 47375888360080

[1278a189-7bf2-466a-97b4-483ea39e3a26] {:size=>5, :connections=>1, :busy=>1, :dead=>0, :idle=>0, :waiting=>0, :checkout_timeout=>5}
[1278a189-7bf2-466a-97b4-483ea39e3a26] Process 61 Thread 47375888360220

[cf61ad32-4e4c-4a9b-a8e4-c770c72ccdb9] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[cf61ad32-4e4c-4a9b-a8e4-c770c72ccdb9] Process 61 Thread 47375888359800

[e58df749-f857-41c4-aead-8bf5141472ab] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[e58df749-f857-41c4-aead-8bf5141472ab] Process 61 Thread 47375888359660

[fe665c36-a2ea-4ce5-929e-a43cf19ce6dc] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[fe665c36-a2ea-4ce5-929e-a43cf19ce6dc] Process 61 Thread 47375888359940

[72338520-7871-4209-a89f-2e8e130a824c] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[72338520-7871-4209-a89f-2e8e130a824c] Process 61 Thread 47375888360080

[1de94e32-0bed-4cec-aa26-80687be54d92] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[1de94e32-0bed-4cec-aa26-80687be54d92] Process 61 Thread 47375888360080

[bd23d3ee-6c75-44e2-b43c-e31b3c6cf31f] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[bd23d3ee-6c75-44e2-b43c-e31b3c6cf31f] Process 61 Thread 47375888360220

[2371fd9d-c8b0-4810-a5d6-442c137a62e3] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[2371fd9d-c8b0-4810-a5d6-442c137a62e3] Process 61 Thread 47375888359660

[410f61bd-ea44-4c3c-af64-fc73bdd9f6b7] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[410f61bd-ea44-4c3c-af64-fc73bdd9f6b7] Process 61 Thread 47375888359940

[de4b597b-ed37-424f-b41f-f30d88e6ba63] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[de4b597b-ed37-424f-b41f-f30d88e6ba63] Process 61 Thread 47375888360080

[eff585ef-7684-435b-8d64-41f0c7f1c90d] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[eff585ef-7684-435b-8d64-41f0c7f1c90d] Process 61 Thread 47375888359800

[356a4a91-7c16-4186-9aa8-5dcd78d3d743] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[356a4a91-7c16-4186-9aa8-5dcd78d3d743] Process 61 Thread 47375888359800

[efd7569a-6f12-4620-a42d-57eeea357d4d] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[efd7569a-6f12-4620-a42d-57eeea357d4d] Process 61 Thread 47375888360220

[07c57d3a-9bab-4dcb-80d4-67105a6f381b] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[07c57d3a-9bab-4dcb-80d4-67105a6f381b] Process 61 Thread 47375888359660

[eaf6e12b-5e1c-4974-862a-b483e40e6cec] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[eaf6e12b-5e1c-4974-862a-b483e40e6cec] Process 61 Thread 47375888359940

[762fe85f-165f-425d-937a-477f822d20b0] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[762fe85f-165f-425d-937a-477f822d20b0] Process 61 Thread 47375888359940

# This is the request that failed. connected_to was called immediately following these logs
[ab4f3ed5-9d2a-4f68-aff4-60794b11521c] {:size=>5, :connections=>1, :busy=>0, :dead=>0, :idle=>1, :waiting=>0, :checkout_timeout=>5}
[ab4f3ed5-9d2a-4f68-aff4-60794b11521c] Process 61 Thread 47375888360080

# Note that connections are gone for the next request
[eda80c15-62ff-47a5-9950-0594dad0a139] {:size=>5, :connections=>0, :busy=>0, :dead=>0, :idle=>0, :waiting=>0, :checkout_timeout=>5}
[eda80c15-62ff-47a5-9950-0594dad0a139] Process 61 Thread 47375888359800
```

### Additional information

The symbol that `current_instance.database_key` returns is added to ActiveRecord::Base.configurations dynamically.  The code to do that is in the database_key method itself:

```
  def database_key
    if ActiveRecord::Base.configurations.configs_for(env_name: database_details["int_name"]).blank?
      Rails.logger.info "Adding configuration for #{database_details["int_name"]} Process: #{Process.pid} Thread: #{Thread.current.object_id}"
      new_config = {
        database_details["int_name"] => {
          "url" => internal_connection_string,
          "adapter"=>"postgresql", 
          "encoding"=>"unicode", 
          "pool"=>5
        }
      }
      new_db_config = ActiveRecord::DatabaseConfigurations.new(new_config)
      ActiveRecord::Base.configurations = (
        ActiveRecord::Base.configurations.configurations + new_db_config.configurations
      )
    end
    # configs_for only works with a string, while connected_to only takes a symbol
    database_details["int_name"].to_sym
  end
```

Note the debug statement there.  I can confirm that the block was only run once for the logs I provided above.  I have no reason to believe this is the problem area since other requests succeed, but think it's worth sharing since I imagine it's unique.

### System configuration
**Rails version**: 6.0.0.beta2

**Ruby version**: 2.5.3

cc @eileencodes and @bogdanvlviv - perhaps you've seen this in development?

**Comment by eileencodes** [comment]
Hey @sidot3291 thanks for the report. The way connected_to / connects_to is implemented in Rails is the exact way we use connection switching at GitHub and have not seen an issue so I'm inclined to think this is something about your implementation (whether that be how you're establishing a connection or swapping a connection)

From this statement "several databases holding the same models" I'm assuming you mean you're using a sharding method. Please correct me if that's not right.

When I implemented this I implemented it as such to support having multiple databases and switching between them. I didn't implement a sharding strategy in Rails because we don't use that at GitHub and I didn't feel I was the right person to implement it. This could be the source of the issue. 

From this report I can't tell what's wrong. Are you able to reproduce this in a sample application for us to take a look? Can you also look at the connection handler and what connections are in the pool?
I'm not sure that the database key can be dynamic like this. The way Rails works is the connection must have it's own connection specification name to swap, otherwise the connection for each database key you have will get overwritten. Inspecting the connection specs in the pool will help us determine if that's happening. You can do `ActiveRecord::Base.connection_handlers[:writing].connection_pool_list.map(&:spec)` to get the spec.

**Comment by sidot3291** [comment]
Thanks @eileencodes 

When Github uses connection switching, do you only pass in a role, or do you pass in a database as well?

Getting under the hood here, I'm seeing that when connected_to receives a database param, it always triggers establish_connection:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_handling.rb#L123

`establish_connection` then disconnects and reconnects without regard to whether the current connection is the same.  As you called out, it looks like this is done because connections are keyed on spec_name, and establish_connection disconnects and reconnects in the process of reassigning the pool for spec_name.
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L954-L974

With regards to the error - my best guess is that I'm hitting some kind of race condition within ConnectionHandler.  The use of finalizers and Concurrent::Map.fetch with a block is a bit beyond my knowledge to really debug, but seem like the only non-atomic(?) operations where this may be introduced.  If this theory is correct, I shouldn't have too hard a time reproducing this in a demo app.  I will try to do that.

To solve my problem though - which is just sharding - it looks like using connected_to with a database param as it's currently implemented is a bad idea.  I don't want frequent disconnections and reconnections, but instead want the connections to be kept alive.

My expectation with connected_to was that, if I called it with a database, Rails would have some internal mapping of database_key to ConnectionPool and would swap to the appropriate pool.  So:
```
ModelA.connected_to(database: :some_database) do
  ModelA.all
end
ModelB.connected_to(database: :some_database) do
  ModelB.all # this would query :some_database without causing reconnection
end
```

Is this a reasonable expectation?  I'm not sure I understand handlers well enough to really judge.

Also, one more question regarding ConnectionHandler to make sure I'm understanding correctly.  Say I have a structure like:
```
class ModelA < ApplicationRecord
  connects_to database: {writing: :write_db, reading: :read_db}
end
class ModelB < ApplicationRecord
  connects_to database: {writing: :write_db, reading: :read_db} # same as above
end
```

Does this result in 2 write_db connections and 2 read_db connections because ModelA and ModelB become spec_names?

Thank you.

**Comment by sidot3291** [comment]
I wasn't able to get sharding working using the new role/database APIs.

My next attempt tried creating a new role for each connection and using `connected_to(role: x)`, but I ran into trouble because `connected_to` changes the current_role on ActiveRecord::Base (via swapping the connection handler).  Since I have some models that are sharded and some that are not, this broke the roles that are not sharded.

I ended up overwriting the connection, connection_pool, connected?, and retrieve_connection methods instead.  This increased my app's speed (presumably since it eliminated reconnections) and I've not hit any peculiar bugs similar to this issue.

I'm not sure if this is helpful, but if I were to pursue a PR I would try:

- Make it so calling `connects_to` in a model (or abstract_class model) overwrites `connection_handler` for that model only (or only it's inheritors).  This new `connection_handler` stores the role to database mapping that's passed into `connects_to`

- Add some notion of `current_pool` as a (thread-safe) attribute on `connection_handler`, and make it so calling `connected_to` changes the `current_pool`.  If `connected_to` receives a database, change current_pool to that specific database's pool.  It if receives a role, look at the internal mapping of role to database from `connects_to` to set current_pool appropriately.

- Add a mapping of database to pool on ActiveRecord::Base.  Make it so connected_to leverages that mapping instead of creating separate pools in each connection_handler.

- Reassess if spec_name still does anything and perhaps simplify connection_pool.

Combined, I believe this would avoid reconnections when passing the database param, make it easier to scope role/database changes to the right set of models, and avoid multiple pools to the same database.

**Comment by eileencodes** [comment]
> When Github uses connection switching, do you only pass in a role, or do you pass in a database as well?

We only pass a role because we use the `database` key for when we need to establish a connection to another database for a specific reason. For example we have a connection that allows slow queries. It's only used in the console and not used in requests.

Were you able to reproduce this in a new Rails application? We usually ask for that because it makes it easier to debug - it's harder for me to debug without it because I then need guess how your models, database, etc are setup.

**Comment by eileencodes** [comment]
I can't reproduce this in a test application with the knowledge I have of the problem and a reproduction from a small app would go a long way towards debugging this. 

It's definitely simpler and not exactly sharding but since I'm not connected to the replicas via handlers it should theoretically create the same problem you're seeing but it is not. Here's the app https://github.com/eileencodes/connected_to_database.

I'm not sure how to adjust the app to recreate the problem, although I am seeing the disconnect and reconnect. I originally designed the connected_to with the database argument to be fore one-off situations (running against a database that allows slow queries) in a Rails console rather than for long-lived swapping. 

As I mentioned I didn't implement sharding (yet) mainly because we don't use sharding at GH and I don't know what the right sharding strategy should be. Reading through your suggested changes I don't think those would work given how connection handling is structured in Rails. 

For this question this is not the right way to do this since the write_db and read_db will open 2 connections to the same database

```ruby
class ModelA < ApplicationRecord
  connects_to database: {writing: :write_db, reading: :read_db}
end
class ModelB < ApplicationRecord
  connects_to database: {writing: :write_db, reading: :read_db} # same as above
end
```

Instead the recommended way is to do this:

```ruby
class ApplicationRecord
  self.abstract_class = true

  connects_to database: {writing: :write_db, reading: :read_db}
end

class ModelA < ApplicationRecord
end

class ModelB < ApplicationRecord
end
```

**Comment by eileencodes** [comment]
Oh I see something strange in the database_key method...


```
    if ActiveRecord::Base.configurations.configs_for(env_name: database_details["int_name"]).blank?
```

What should `database_details["int_name"]` return? Does it return just a number? What does your database.yml look like?

**Comment by sidot3291** [comment]
Thanks for combing through this, @eileencodes 

Here's a demo app that throws the error reliably:
https://github.com/sidot3291/multidberror

In console, run:
```
AbstractFoo.connected_to(database: :development){ Bar.first }
```

Note: `AbstractFoo` is an abstract model that `Bar` does not inherit from.

Interestingly, this does not throw the error, even though "writing" role isn't defined anywhere:
```
AbstractFoo.connected_to(database: {writing: :development}){ Bar.first }
```

I haven't done more investigation into why my original use case was behaving like a race condition or thread safety error (e.g. some loads hit the error, some didn't), but hopefully this helps.

Regarding your ModelA/ModelB example:  Is it a bug that this opens multiple connections?  The pool setting in database.yml sets an expectation for how many connections will be opened, and this functionality overrides that setting by creating multiple pools.

You can see this by running:
```
(0..5).map{ ActiveRecord::Base.connection_pool.object_id }
 => [70136453718420, 70136453718420, 70136453718420, 70136453718420, 70136453718420, 70136453718420]
```
(all the same object)

vs:
```
> (0..5).map{ ActiveRecord::Base.connected_to(database: :development) { ActiveRecord::Base.connection_pool.object_id } }
 => [70136468950680, 70136468949660, 70136468948660, 70136468947660, 70136454717120, 70136454716120] 
```
(all different objects)

Please let me know how I could be more helpful.  I've rolled my own sharding solution for now, but would prefer if we can make it work natively.  I really like the connected_to API and using it feels natural.

**Comment by sidot3291** [comment]
database_details["int_name"] returned a string.  That block of code was how I added configurations dynamically, in lieu of using database.yml

**Comment by eileencodes** [comment]
Ok I see the problem. This won't work

> AbstractFoo.connected_to(database: :development){ Bar.first }

You have to assign the database to a role/handler (that's the `:writing` key) or else the connection cannot be established.

I will update Rails to fix this because it should fail more gracefully or pick up the default handler.

> AbstractFoo.connected_to(database: {writing: :development}){ Bar.first }

Does not throw the error because you are giving it a role/handler to use.

> Is it a bug that this opens multiple connections?

Not technically. You might want this behavior for one or two models for some reason, you just don't want to open a connection for every single model to the same database. There will be side effects.

**Comment by eileencodes** [comment]
Actually I know the problem and it's not _exactly_ what I said it was. If you call `ApplicationRecord.connected_to(database: :development){ Bar.first }` first `AbstractFoo.connected_to(database: :development){ Bar.first }` won't fail in the console anymore. I think I know what it is and will push a change soon.

Thanks for providing the sample app, it helps a lot!

**Comment by sidot3291** [comment]
Great!  Yes, I think this comment resolved that it should work without a role:
https://github.com/rails/rails/pull/34052#issuecomment-426446991

Re: multiple pools: it makes more sense to me that `connected_to()` would adhere to the pool setting in database.yml than create an additional pool.

In the case where someone intentionally wants to create an additional pool, I'd prefer something that more explicitly warns of the side effects like `connected_to_new_pool()`

I'm just one person with a heavy bias towards sharding, though.  The way GH uses this, are there downsides to sharing a pool for connected_to()?

**Comment by eileencodes** [comment]
> Re: multiple pools: it makes more sense to me that connected_to() would adhere to the pool setting in database.yml than create an additional pool.

I think we're confusing terminology here. When I say pool I mean this pool https://github.com/rails/rails/blob/b1fc1319dfbc450451bb0b410113dd6b7ab1d412/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb which has existed for a long time and has not changed with multiple databases.

The only thing I changed beyond adding new methods for swapping or establishing multiple connections is the ability to assign pools to a role. So when you connect to the database to write you have a list of connections in the writing connection handler that you can swap from. Then you have a reading handler that has read only connections so that it's easy to know which one you're grabbing from the pool. Even if I hadn't implemented multiple handlers and implemented a way to have 2 kinds of connections in the pool they would still be separate connections because your reading databases should have a readonly user, separate from the user your writing databases are using.

**Comment by sidot3291** [comment]
Hmm, I'm hitting a wall here.  I think I see why multiple databases and sharding are at odds, but the functionality is similar enough that it feels like there should be an elegant abstraction to handle both.

Do you imagine a shard being configured as a role, a database, or neither?  And given that, how would you make it so each shard supports multiple roles?

Say we configure each shard as a database with optional, multiple roles, e.g:
```
#database.yml

shard1:
  writing:
    url: "postgres://write@localhost/shard1"
  reading:
    url: "postgres://read@localhost/shard1"

shard2:
  writing:
    url: "postgres://write@localhost/shard2"
  reading:
    url: "postgres://read@localhost/shard2"

shard3:
  url: "postgres://write@localhost/shard3"
```

Then we can make it so connected_to takes both the database and the role:
`Model.connected_to(database: :shard2, role: :writing)`

Or if there aren't roles, just the database:
`Model.connected_to(database: :shard2)`

Issue is, this is _way_ less elegant for GitHubs use case, since you only want to pass in `role`.

And also, suddenly this feels like it could be quite far away for a resolution by 6's release.

**Comment by eileencodes** [comment]
I need to spend some time thinking about your use case. I don't know that it's the right way to implement sharding for Rails 6 or not. I've not used sharding in production so it's harder for my to determine what the _right_ way is.

I will get back to you soon.

**Comment by itsWill** [comment]
Hi @eileencodes, I work with @rafaelfranca and am currently building on top of some of the work @gmcgibbon started.  At shopify we take an approach similar to what @sidot3291 mentioned above.

Where our configuration looks something like:

``` yaml
production:
  <% Sharding.local_shard_ids.each do |shard_id| %>
    shard_<%= shard_id %>:
      username: shopify_writer
      database: shopify_shard_<%= pod_id %>
      password: "password"
      host: "host"

    shard_<%= shard_id %>_readonly:
      username: shopify_reader
      database: shopify_shard_<%= shard_id %>
      password: "password"
      host: "host"
  <% end %>
```

Then we have app level code the connections for the shards.

I've thought about ways we can improve this and came up with some ideas:

 <details>
   <summary> Introduce the concept of a <code>group</code> and <code>topology</code> key to manage yaml configuration </summary>

   The config would look like this. Where a database group is specified by the `shard_*` keys.

   ``` yaml
   production:
    topology: group
    shard_1:
      reading:
        url: "reading_database_url"
      writing:
        url: "writer_database_url"
    shard_2:
      reading:
        url: "reading_database_ulr"
      writing:
        url: "writer_database_url"
   ```

   Then instead of modifying the `connected_to` method to be able to handle both a `database` and a `role` we can introduce a `connected_to_group(group:, role:)` method that connects to a `role` in
   a specified `group`.

   A naive implentation could look like something in this patch:
   <details>
    <summary> <code>connected_to_group</code> implementation example</summary>

``` patch
      From 1cace6405fe6975a2dc9d472610dfeefc51eb7c6 Mon Sep 17 00:00:00 2001
From: Guilherme Mansur <guilherme.mansur@shopify.com>
Date: Thu, 11 Apr 2019 09:23:31 -0400
Subject: [PATCH] wip

---
 .../lib/active_record/connection_handling.rb  | 24 ++++++++++++++-
 activerecord/lib/active_record/core.rb        |  4 +++
 .../connection_handlers_multi_db_test.rb      | 29 +++++++++++++++++++
 3 files changed, 56 insertions(+), 1 deletion(-)

diff --git a/activerecord/lib/active_record/connection_handling.rb b/activerecord/lib/active_record/connection_handling.rb
index 53069cd899..c247d1c490 100644
--- a/activerecord/lib/active_record/connection_handling.rb
+++ b/activerecord/lib/active_record/connection_handling.rb
@@ -130,6 +130,22 @@ def connected_to(database: nil, role: nil, &blk)
       end
     end

+    def connected_to_group(group:, role:, &blk)
+     handler = connection_handler_for_group(group: group, role: role)
+     swap_connection_handler(handler, &blk)
+    end
+
+    def connection_handler_for_group(group:, role:)
+      group_connection_handlers[group] ||= begin
+        handler_key = "#{group}-#{role}".to_sym
+        lookup_connection_handler(handler_key)
+      end
+    end
+
+    def current_group
+      group_connection_handlers.key(connection_handler)
+    end
+
     # Returns true if role is the current connected role.
     #
     #   ActiveRecord::Base.connected_to(role: :writing) do
@@ -150,7 +166,13 @@ def connected_to?(role:)
     #     ActiveRecord::Base.current_role #=> :reading
     #   end
     def current_role
-      connection_handlers.key(connection_handler)
+      handler_key = connection_handlers.key(connection_handler)
+
+      if topology == :group
+        handler_key.split('-').last
+      else
+        handler_key
+      end
     end

     def lookup_connection_handler(handler_key) # :nodoc:
diff --git a/activerecord/lib/active_record/core.rb b/activerecord/lib/active_record/core.rb
index eb4b48bc37..6259350582 100644
--- a/activerecord/lib/active_record/core.rb
+++ b/activerecord/lib/active_record/core.rb
@@ -125,6 +125,10 @@ def self.configurations

       mattr_accessor :connection_handlers, instance_accessor: false, default: {}

+      mattr_accessor :topology, instance_accessor: false, default: :default
+
+      mattr_accessor :group_connection_handlers, instance_accessor: false, default: {}
+
       mattr_accessor :writing_role, instance_accessor: false, default: :writing

       mattr_accessor :reading_role, instance_accessor: false, default: :reading
diff --git a/activerecord/test/cases/connection_adapters/connection_handlers_multi_db_test.rb b/activerecord/test/cases/connection_adapters/connection_handlers_multi_db_test.rb
index 36591097b6..3fe06740f6 100644
--- a/activerecord/test/cases/connection_adapters/connection_handlers_multi_db_test.rb
+++ b/activerecord/test/cases/connection_adapters/connection_handlers_multi_db_test.rb
@@ -203,6 +203,35 @@ def test_switching_connections_without_database_and_role_raises
           assert_equal "must provide a `database` or a `role`.", error.message
         end

+        def test_connected_to_group_connects_to_the_specified_group
+          previous_env, ENV["RAILS_ENV"] = ENV["RAILS_ENV"], "default_env"
+
+          config = {
+            "topology" => "group",
+            "default_env" => {
+              "group_a" => {
+                  "primary" => { "adapter" => "sqlite3", "database" => "db/primary_a.sqlite3" },
+                  "replica" => { "adapter" => "sqlite3", "database" =>"db/readonly_a.sqlite3" }
+                },
+              "group_b" => {
+                  "primary" => { "adapter" => "sqlite3", "database" => "db/primary_b.sqlite3" },
+                  "replica" => { "adapter" => "sqlite3", "database" => "db/primary_a.sqlite3" }
+                }
+              }
+            }
+
+          @prev_configs, ActiveRecord::Base.configurations = ActiveRecord::Base.configurations, config
+
+          ActiveRecord::Base.connected_to_group(group: :group_a, role: :readonly) do
+            assert_equal :readonly, ActiveRecord::Base.current_role
+            assert_equal :group_a, ActiveRecord::Base.current_group
+          end
+        ensure
+          ActiveRecord::Base.configurations = @prev_configs
+          ActiveRecord::Base.establish_connection(:arunit)
+          ENV["RAILS_ENV"] = previous_env
+        end
+
         def test_switching_connections_with_database_symbol
           previous_env, ENV["RAILS_ENV"] = ENV["RAILS_ENV"], "default_env"

--
2.19.1
```
</details>


  What I like about this approach is:

  * that visually its very clear how the DBs are arragenged.
  * by having a key that identifies the arrangement its easier to parse and validate the configuration into a `DatabaseConfiguration`, since we can know right away what configuration to expect.
  * it's backwards compatible and explicit, we can default the `topology` key to `single` (or if its missing for old apps) for new rails apps, and if it's some value like `primary_replica` we can assume it's in the configuration used at github. When upgrading the arrangement we are explicity in our configuration.
  * the `connected_to` method stays the same so the behaviour is backwards compatible.

The downside I see is:

* we introduce a new concept of `group`.
* I'm not sure if the word topology is clear or good enough for the yaml key.


</details>

 <details>
 <summary> Specify the yaml file without the toplevel <code> topology </code> key </summary>

 The yaml file would look just like the one posted by @sidot3291 the biggest downside there is that to parse the config, we can assume that if we have three levels of nesting we are parsing a group config. 
 
 The downsides I see are: 

 * I'm not sure if that is a safe assumption to make
 * It's also a bit trickier to parse.

</details>

 <details>

 <summary> Add a <code> group </code> key to the <code>reader</code> <code>writer</code> configs</summary>

 The yaml config would look like:

 ``` yaml
 production:
   reader:
     database: "reader_database_url"
     group: "shard_1"
   writer:
     database: "writer_database_url"
     group: "shard_1"
   reader:
     database: "reader_database_url"
     group: "shard_2"
   writer:
     database: "writer_database_url"
     group: "shard_1"
```

The downside I see here is: 

* that this is not as visually clear what kind of arrangement we have 
* there is a lot of redundant specification of the `group`. 
* The parsing is of the YAML is as complex as the other approaches.

</details>

My preference was on the first approach, which I found the most clear and maintainable.

**Comment by eileencodes** [comment]
@itsWill can you build a test app that represents a similar approach to how Shopify is set up currently so I can play around with it? It's hard for me to look at the code and know what the right API feels like since we don't use sharding at GitHub so a test app would help a ton.

**Comment by itsWill** [comment]
For sure, I'll dig in and chat around a bit and see if I can get you the most representative example 👌

**Comment by itsWill** [comment]
👋 @eileencodes I have a test app here! https://github.com/itsWill/sharded_app the README should have the setup instructions. 

A bit of context:

At Shopify the `yml` we have looks like the `database.yml` in the app. We have a bunch of shards that are sharded by `shop_id` and then an unsharded `master` table.

We implemented our own connection switching API using abstract classes doing something like:

``` ruby
def connection_name_for(connection_name)
  if klass = existing_connection_class_for(connection_name)
    return klass
  end

  klass = Class.new(ActiveRecord::Base) do
    self.abstract_class = true
  end

  shard_name = shard_name_for(connection_name)

  const_set(shard_name, klass)
  config = configuration_for(connection_name)
  klass.establish_connection(config)
  klass.connection_pool.spec.config[:connection_name] = connection_name # we store the name in the config so we can refer to the connection by name
  klass
end

def existing_connection_class_for(connection_name)
 shard_name = shard_name_for_connection(connection_name)
 if const_defined?(shard_name, false)
   return const_get(shard_name, false)
 end
end
```

This means every that for shard N we'll have a `ShardN` abstract class and so on for the other shards, these are then cached in memory, since these connections are associated with the abstract class they are never released back into the pool, this works at Shopify because the application runs on unicorn and is single threaded.

When a request comes in to Shopify we have an NGINX module that annotates the request with a custom header `X-SHARD-ID`  before the request hits the app and then we retrieve the connection based on that header.

Depending on the type of `SQL` query we're doing we can route to the `shard_1_primary` for writes and the `shard_1_replica` for reads, we implemented a sticky writer pattern on top of this connection switching API.


I've implemented the general idea of what we do with a custom `DatabaseSelector::Resolver` middleware in the test app that mimics a similar middleware we have within Shopify.


With regards to migrations, at Shopify we mark the migration files with whether they are for sharded tables or the master tables with an API like:

``` ruby
class CreateShops < ActiveRecord::Migration[6.0]
  mark_as_master_migration! # alternatively mark_as_sharded_migration!

  create_table :shops do |t|
    t.timestamps
  end
end
```

We then override the connection method in `ActiveRecord::Migration` to return the connection corresponding to shard we want to connect.

I've implemented something similar within the test application to show the high level api.

With regards to fixtures we have a directory structure like:

`fixtures/shard_0/orders.yml` and `fixtures/shard_1/orders.yml` and the fixtures are then loaded by shard.

There is this [PR](https://github.com/rails/rails/pull/33945) by @gmcgibbon currently in progress that has a nicer API IMO since we can duplicate fixtures by setting the path to be the same rather than copying fixture files.

**Comment by kjvarga** [comment]
@eileencodes we're switching to Rails 6 for the new replication support.  I really appreciate your work on this.  We are more than excited to be rid of Octopus which has caused some issues for us.  I have a simple question that I think you would be best to explain.

The setup is simple.  We have a `reading` role and `writing` role.  With a db configuration for each that looks like:

`config/database.yml`:
```yml
common: &common
  adapter: mysql2
  host: change-mysql
  port: 3306
  password:
  encoding: utf8

development:
  writer:
    <<: *common
    username: root
    database: promotion_service_devel
  read_replica:
    <<: *common
    username: readonly
    database: promotion_service_devel
    replica: true
```

`app/models/application_record.rb`:
```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :writer, reading: :read_replica }
end
```

In the example below, when I try to execute a query against the connection while within the `reading` role, I get a `ActiveRecord::ConnectionNotEstablished` error:

```ruby
irb(main):110:0> ActiveRecord::Base.connected_to(role: :reading) { ActiveRecord::Base.connection.execute('SELECT 1'); }
Traceback (most recent call last):
        2: from (irb):110
        1: from (irb):110:in `block in irb_binding'
ActiveRecord::ConnectionNotEstablished (No connection pool with 'primary' found for the 'reading' role.)
```

But if I establish the connection first then it works:
```ruby
ActiveRecord::Base.connected_to(role: :reading) { ActiveRecord::Base.establish_connection; ActiveRecord::Base.connection.execute('SELECT 1'); }
   (1.2ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.9ms)  SELECT 1
=> #<Mysql2::Result:0x00007ff25257c410 @query_options={:as=>:array, :async=>false, :cast_booleans=>false, :symbolize_keys=>false, :database_timezone=>:utc, :application_timezone=>nil, :cache_rows=>true, :connect_flags=>2148573701, :cast=>true, :default_file=>nil, :default_group=>nil, :adapter=>"mysql2", :host=>"change-mysql", :port=>3306, :password=>nil, :encoding=>"utf8", :username=>"root", :database=>"promotion_service_devel", :flags=>2}, @server_flags={:no_good_index_used=>false, :no_index_used=>false, :query_was_slow=>false}>
```

For the `writing` role I don't have this problem, because it is the "default" connection.  I'm wondering if there's a proper way to get a connection from the current pool?  But shouldn't `ActiveRecord::Base.connection` be set to a connection from the pool when specifying a (new) role?

Thanks,
Karl

**Comment by eileencodes** [comment]
@kjvarga your issue will be fixed in rc2 with the addition of https://github.com/rails/rails/pull/36394.

**Comment by juny4ng** [comment]
@sidot3291 did you manage to find a workaround this? i'm experimenting with multi db support for sharding and running into a similar issue.

**Comment by lizdeika** [comment]
the issue is still present in 6.0.0 release

code in controller which randomly yields to error:

```ruby
ActiveRecord::Base.connected_to(database: { reading: :primary }) do
  User.where(id: 1).pick(:id)
end
```

```ActiveRecord::ConnectionNotEstablished: No connection pool with 'primary' found for the 'reading' role.```

Error is random in production env, not on every request

**Comment by lizdeika** [comment]
easy to reproduce in rails console

ERROR
```bash
$ bin/rails c
Loading development environment (Rails 6.0.0)
irb: warn: can't alias context from irb_context.
irb(main):001:0> ActiveRecord::Base.connected_to(role: :reading) { pp ActiveRecord::Base.connection.instance_variable_get(:@config) }
Traceback (most recent call last):
        2: from (irb):1
        1: from (irb):1:in `block in irb_binding'
ActiveRecord::ConnectionNotEstablished (No connection pool with 'primary' found for the 'reading' role.)
irb(main):002:0>
```

NO ERROR
```bash
$ bin/rails c
Loading development environment (Rails 6.0.0)
irb: warn: can't alias context from irb_context.
irb(main):001:0> ActiveRecord::Base.connected_to(database: { reading: :primary }) { pp ActiveRecord::Base.connection.instance_variable_get(:@config) }
   (1.6ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
{:prepared_statements=>false,
 :adapter=>"mysql2",
 :encoding=>"utf8",
 :pool=>25,
 :host=>"127.0.0.1",
 :port=>3357,
 :username=>"root",
 :password=>nil,
 :database=>"app_development",
 :flags=>2}
=> {:prepared_statements=>false, :adapter=>"mysql2", :encoding=>"utf8", :reconnect=>false, :pool=>25, :host=>"127.0.0.1", :port=>3357, :username=>"root", :password=>nil, :database=>"spp-ninja_development", :flags=>2}
irb(main):002:0>
```

is this expected behaviour?

**Comment by eileencodes** [comment]
@lizdeika without seeing your app or an example app it's hard to say exactly what is wrong, but I have a guess.

It seems like you're not establishing a connection on boot in the models. Please read the documentation here: https://guides.rubyonrails.org/active_record_multiple_databases.html

You need to establish a connection with `connects_to` in your models like:

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: { writing: :primary, reading: :primary_replica }
end

class Dog < ApplicationRecord
end
```

Then in your controller use `role`

```ruby
ActiveRecord::Base.connected_to(role: :reading) do 
  Dog.first
end
```

I do not recommend using `connected_to(database: :primary_replica)` in a controller action. That should only be used for one-off connections because it will re-establish a connection every time. 

At this time Rails does not support sharding if that's the reason you're using `connected_to(database: :reading)`.

**Comment by lizdeika** [comment]
Thank you!
I was missing the `ApplicationRecord` roles setup, did not realize that roles must be provided explicitely there.

I did it like this
```ruby
connects_to database: { writing: :primary, reading: :primary, reading_replica: :primary_replica }
```

This way primary database is used everywhere and I can manually do the readings where needed like this:
```ruby
ActiveRecord::Base.connected_to(role: :reading_replica) do
  # read
end
```

**Comment by eileencodes** [comment]
Why are you duplicating connections to the primary?

```
connects_to database: { writing: :primary, reading: :primary, reading_replica: :primary_replica }
```

Should be:

```
connects_to database: { writing: :primary, reading: :primary_replica }
```

**Comment by lizdeika** [comment]
I want to use primary database for models by default

```
connects_to database: { writing: :primary, reading: :primary_replica }
```

wouldn't this use a replica database for models by default for reading operations?

**Comment by eileencodes** [comment]
> wouldn't this use a replica database for models by default for reading operations?

Yes, but if you want to read from the primary, just read from the primary. Duplicating connections will have side effects and you won't be able to effectively utilize the provided middleware. There's no up-side to duplicating the connection so you can read from the primary when you can just read from the writing role.

Thinking of "writing" as "default" - a normal database connection with no restrictions and "reading" should be a replica, always. Otherwise it's not useful.

**Comment by sqlninja** [comment]
I just want to chime in (and create a new issue if needed)...

I consistently get `ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode:` exceptions thrown even though I have wrapped the code in a connected_to block...

For example:
I have a status column on a Message model that gets updated at render time based on the status of child records.

```
  def status
    # I have also tried it this way
    # ApplicationRecord.connected_to(role: :writing) do
    Message.connected_to(role: :writing) do
    # NOTE: status is a calculated field based on the individual messages
    current_status = self[:status]
    unless %w[Deleted Archived Draft Rejected 'Pending Approval' Paused].include?(current_status)

      recipient_statuses = message_recipients.select(:status, :send_at)
      # Possible updatable states are: Pending, In Progress, Sent, Error, Cancelled
      current_status = if recipient_statuses.any? { |r| r.status == 'cancelled' } then 'Cancelled'
                       elsif recipient_statuses.all? { |r| r.status == 'sent' } then 'Sent'
                       elsif recipient_statuses.any? { |r| r.status == 'in progress' } || (recipient_statuses.any? { |r| r.status == 'pending' }) && recipient_statuses.any? { |r| r.send_at.present? && r.send_at <= Time.now } then 'In Progress'
                       elsif recipient_statuses.any? { |r| r.status == 'error' } then 'Error'
                       elsif recipient_statuses.all? { |r| r.status == 'pending' } || recipient_statuses.all? { |r| r.send_at.present? && r.send_at >= Time.now } then 'Pending'
                       end
    end

      update_attributes!(status: current_status) # << This is throwing an error

    current_status
    end
  end
```

My ApplicationRecord is super basic:
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary, reading: :follower }
end
```

Am I missing something?
I have other areas that this happens as well and for now, I'm just eating the exception, mostly where events are being logged (using Ahoy)

**Comment by lizdeika** [comment]
> > wouldn't this use a replica database for models by default for reading operations?
> 
> Yes, but if you want to read from the primary, just read from the primary. Duplicating connections will have side effects and you won't be able to effectively utilize the provided middleware. There's no up-side to duplicating the connection so you can read from the primary when you can just read from the writing role.
> 
> Thinking of "writing" as "default" - a normal database connection with no restrictions and "reading" should be a replica, always. It's restrictions are enforced locally by creating a readonly user for it. Otherwise it's not useful.

Thanks! I think I understand it now, I just did like this:
```
connects_to database: { reading_replica: :primary_replica }
```

To be able todo: 
```ruby
ActiveRecord::Base.connected_to(role: :reading_replica) do
  # read
end
```
where I manually need reading from replica

**Comment by eileencodes** [comment]
Alright this issue is getting kind of out of hand. There are 3 problems being discussed at once. Unfortunately I don't have time to debug problems without reproduction scripts. That's the only way I can help you. Rails also doesn't use issues as a help support forum, please use stack overflow for that. 

---

@sqlninja - if you're using the middleware and status is a get request you need to turn off preventing writes like this:

```ruby
ActiveRecord::Base.connected_to(role: :writing) do |handler|
  handler.while_preventing_writes(false) do
    # the rest of your stuff
end
```

Since you're having a completely different issue than the error reported here, please open a new issue with a reproduction application if you continue to have issues.

---

@lizdeika Rails is designed to do the connection switching for you except in cases where you need a specific behavior. You should connect your regular replica like I demonstrated before. If you have some other replica using a role with a name that's not `reading` will mean the switcher won't work unless you tell Rails to do a different `reading_role` name. But if you want this to be really manual that's fine you can do that.

**Comment by eileencodes** [comment]
I'm closing this because I don't think this is an issue anymore. In all the cases it was an app incorrectly connecting to the database.

**Comment by lizdeika** [comment]
Yes that's what I need. A default behavior for primary database(read/write) and manual replica reading where needed.

I think there is a place for improvement in the documentation. Maybe some examples of usage cases how to achieve them.

**Comment by ocha** [comment]
> I wasn't able to get sharding working using the new role/database APIs.
> 
> My next attempt tried creating a new role for each connection and using `connected_to(role: x)`, but I ran into trouble because `connected_to` changes the current_role on ActiveRecord::Base (via swapping the connection handler). Since I have some models that are sharded and some that are not, this broke the roles that are not sharded.
> 
> I ended up overwriting the connection, connection_pool, connected?, and retrieve_connection methods instead. This increased my app's speed (presumably since it eliminated reconnections) and I've not hit any peculiar bugs similar to this issue.
> 


@sidot3291 Do you have a sample app or gist of what those overrides look like? I am trying to solve similar problem where I want to switch between database servers beginning  of request.

**Comment by aledalgrande** [comment]
I had a similar issue and this is how I read/write on the primary by default and then use the follower for only certain queries:

```rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary, reading: :primary }
end
```

and then sporadically use this in the code:
```rb
ActiveRecord::Base.connected_to(role: :reading) do
  # read
end
```

**Comment by nvzard** [comment]
@aledalgrande were you able to resolve this issue? I am facing the same problem.

**Comment by aledalgrande** [comment]
@nvzard the code above works for me.

**Comment by vishal91** [comment]
The above code says `reading: primary`. Will it read from primary or primary_replica in case of using it on certain query 

ActiveRecord::Base.connected_to(role: :reading) do
  # read
end
