### ISSUE TITLE
Rails.application.eager_load! regression in Zeitwerk autoloader mode

### ISSUE THREAD

**Issue by JeremiahChurch** [rails/rails#37006]
https://github.com/rails/rails/blob/master/railties/lib/rails/engine.rb#L474
there is a note
>  Already done by Zeitwerk::Loader.eager_load_all in the finisher.

This doesn't appear to be true outside of production modes.

It's fairly common to eager load (`Rails.application.eager_load!`) for rake tasks or other reason in lower environments but the behavior with zeitwerk is different than in classic mode.

I believe adjusting the line beneath the comment from `return if Rails.autoloaders.zeitwerk_enabled?`

to `return Zeitwerk::Loader.eager_load_all if Rails.autoloaders.zeitwerk_enabled?` returns the behavior to the previous, but I'm unsure of other implications.

### Steps to reproduce
```
rails new autoload
cd autoload
rails c
>
Rails.application.eager_load!
> nil
ActiveRecord::Base.descendants
> []
```

### Expected behavior
in same app as above - edit config/application.rb
add `config.autoloader = :classic` directly beneath `config.load_defaults 6.0`
save & exit
```
rails c
>
Rails.application.eager_load!
> ["/home/tongboy/autoload/autoload/app/channels", "/home/tongboy/autoload/autoload/app/controllers", "/home/tongboy/autoload/autoload/app/controllers/concerns", "/home/tongboy/autoload/autoload/app/helpers", "/home/tongboy/autoload/autoload/app/jobs", "/home/tongboy/autoload/autoload/app/mailers", "/home/tongboy/autoload/autoload/app/models", "/home/tongboy/autoload/autoload/app/models/concerns"]
ActiveRecord::Base.descendants
> [ApplicationRecord(abstract)]
```

similarly - if classic mode is not enabled and instead just `Zeitwerk::Loader.eager_load_all` is called rather than the `Rails.application.eager_load!` then the 'good' behavior is also seen.

To me this looks like a regression in the behavior of `Rails.application.eager_load!` in non-classic mode - matching the long-standing behavior seems to make the most sense, but I'm far from an expert in auto loading and just working on fixing up some gems for rails 6 support.

Please let me know if pulling together a PR or any additional information around this would be helpful.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3p62

**Comment by pond** [comment]
Bump on this. We used (past tense!) reflection quite a lot but on moving to Rails 6 under Zeitwerk, it all went wrong (dev mode - not in Production, thankfully). We even had cases as severe as this:

* A base class defines some mandatory methods that all just raise "NotImplementedError"
* Subclasses implement (override) all of those methods
* An iterator over the base class `.descendants` is used in a test which instantiates the subclasses and calls one of the methods under test
* When we ran these unit tests individually, all was fine
* When we ran the whole suite, we'd get intermittent NotImplementedError exceptions - different every time, by seed - but this is impossible, unless somehow `.descendants` had enumerated _the base class_ not a descendant, indicating a pretty horrible Zeitwerk failure.

We could've just eager-loaded the whole application, but that's very slow. It's when we first realised that `Rails.application.eager_load!` didn't work anymore, too; fortunately this very bug report led us to the solution of using `Zeitwerk::Loader.eager_load_all`. We tried using `require` and a few other tricks that worked under the classic autoloader, but it just didn't help. In the end we resolved it by losing a benefit of Ruby - we stopped doing reflection, instead hand-maintaining lists of subclasses in constants which are iterated over instead. This works reliably.

We are sticking with Zeitwerk since it's recommended for Rails 6, but only with a sense of unease - we've seen too many weird bugs in dev that don't happen if you change to the classic autoloader. This is a new application built under Rails 5.2 just a couple of months before 6.0 was released and I'm pretty sure we're not doing anything particularly strange :-) - just feels like Zeitwerk wasn't quite ready for prime-time.

Fingers crossed for some fixes soon. If there's anything that could be added here which might aid debugging at least this core issue with `Rails.application.eager_load!`, let me know.

**Comment by kddeisz** [comment]
You can put this in an initializer and not change any of your code:

```ruby
module Rails
  class Application
    def eager_load!
      Zeitwerk::Loader.eager_load_all
    end
  end
end
```

It's not an ideal solution, but it should ease migration without you having to change a bunch of reflection.

**Comment by pond** [comment]
@kddeisz Thanks, but the problem isn't really that forcing eager-load-all has changed API, that's just one aspect; but also that when you do it, under Zeitwerk things _still don't work_ when reflection is used, with some truly disturbing "impossible for normal Ruby" things such as a call to `descendants` including the base class itself, not just its descendants, in the returned enumerable.

**Comment by kddeisz** [comment]
@pond Interesting - I can't replicate that behavior. If that were the case it would be a bug with Rails itself not "normal Ruby" though, since descendant tracking is handled within ActiveSupport. Do you have a way of replicating the `descendants` issue?

**Comment by pond** [comment]
@kddeisz Replication - good question and I was hoping nobody would ask it, but instead say "ah-ha! I know what that is" :joy: - currently only happens in our full Rails code base which is proprietary so I can't share it. When I have some time, I'll have a go at replicating it for a small-as-possible test case.

**Comment by pedrofurtado** [comment]
@fx @rafaelfranca Any news about this issue? A workaround, for a while, is to replace `Rails.application.eager_load!` to `Zeitwerk::Loader.eager_load_all` 👍

**Comment by fxn** [comment]
@pedrofurtado yeah, sorry but took a Christmas hiatus. It's in my plate.

**Comment by pedrofurtado** [comment]
@fxn No problem 🤝 Anyway, thanks for you hard work in Zeitwerk and its integration in Rails 🏆 It`s a great gem

**Comment by fx** [comment]
How confusing would it be, if I was actually on the rails core team? :P

**Comment by fxn** [comment]
I have implemented a minimal regression patch in https://github.com/rails/rails/commit/3285f3df7bc3a7a978428044b5458f1eed30b1a9.

Could you folks try that one out?

**Comment by kddeisz** [comment]
@fxn this works for me

**Comment by fxn** [comment]
I believe this is good as a compromise, have registered in the CHANGELOG and have cherry-picked it to `master`.

**Comment by pond** [comment]
Good to see the OP issue resolved. If I'm able to get a simple reproduction case for the additional issues I encountered, I'll submit a new bug report with that included.

**Comment by rgaufman** [comment]
I tried to run  Zeitwerk::Loader.eager_load_all -- but when I run Mongoid.models it is still missing most of my models and just shows the first one:
```
tether-it(prod)> Mongoid.models
=> [Mongoid::GridFs::Fs::File, Mongoid::GridFs::Fs::Chunk, Doorkeeper::AccessGrant, Doorkeeper::AccessToken, Doorkeeper::Application, Brand]
```

Any ideas?

**Comment by fxn** [comment]
Can you please put `Rails.autoloaders.log!` in `config/application.rb`, reproduce, and share the results specifying some particular model class you're missing?

**Comment by rgaufman** [comment]
This is on our production system, so I won't be able to for a few days, but I added this workaround for the time being:

```ruby
    mongo_models = `find app/models -type f | while read line; do egrep -H "Mongoid::Document" "$line"; done`
    mongo_models.split("\n").each do |line|
      name = line.split(':')[0].split('/')[-1].split('.')[0].capitalize
      name.constantize
    end
```

This then loads all my models, but is a pretty messy solution :(

**Comment by fxn** [comment]
@rgaufman that is very strange. When does that code run?

**Comment by rgaufman** [comment]
Just in rails c - I either copy paste or now I put it in a file so I can require it and run. I also tried running as rails runner migrate.rb

**Comment by fxn** [comment]
@rgaufman I am not familiar with this gem, but do you have set `preload_models` to be `false` in its configuration?

**Comment by byroot** [comment]
No activity in a year. I'll close.
