### ISSUE TITLE
Rails 6 - "no _dump_data is defined"  - Running test suite wipes test database's views and functions

### ISSUE THREAD

**Issue by thornomad** [rails/rails#38279]
_As I am working to upgrade from 5.2 to 6.0 (postgresql@10.11) and I ran into trouble with the test database having its `views` and `functions` wiped whenever tests were run._ 

### Steps to reproduce
Here are the minimal steps to reproduce the issue with a migration and test that will pass (as expected) in 5.2 but fails in 6.0.

```fish
# ruby -v 2.6.3
rails _6.0.2.1_ new test-app-6 -d=postgresql
rails _5.2.4.1_ new test-app-5 -d=postgresql
```

Then, in each newly created app, add the following migration and unit test:

```ruby
# db/migrate/xxxx_create_table_and_view_for_testing.rb
class CreateTableAndViewForTesting < ActiveRecord::Migration[5.2] # or [6.0] !
  class Person < ApplicationRecord; end

  def up
    create_table :people do |t|
      t.string :name
    end

    # Simple view that should persist
    connection.execute <<-SQL
      DROP VIEW IF EXISTS view_people;
      CREATE OR REPLACE VIEW view_people AS
        SELECT id, name
        FROM people
    SQL

    # Seed the database with some values
    (1..5).each { |i| Person.create!(name: "Person ##{i}") }
  end

  def down
    connection.execute <<-SQL
      DROP VIEW IF EXISTS view_people;
    SQL
    drop_table :people
  end
end

# test/models/person_test.rb
require 'test_helper'

class PersonTest < ActiveSupport::TestCase

  class Person < ApplicationRecord; end

  class ViewPerson < ApplicationRecord
    self.table_name = 'view_people'
  end

  test 'there are five seeded people' do
    assert_equal 5, Person.count
  end

  test 'there are five people in the view' do
    assert_equal 5, ViewPerson.count
  end

end
```

Then you can run these both in each app.  
```
# in each newly created app
bundle exec db:create
bundle exec db:migrate RAILS_ENV=test
bundle exec rake
```

### Expected behavior
I would expect the tests to pass, as they do in the 5.2 app for me.

### Actual behavior
In the 6.0 app they fail and, as a result of the test running, the `view_people` view is dropped and the `people` table is empty.Which does not happen in 5.2.

Two things I noticed:

1) If I happen to have a database connection open to the test database (using Navicat, for example) then in 6.0 then it complains:

>ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "test_app_6_test" is being accessed by other users
>DETAIL:  There is 1 other session using the database.

When this happens, the postgres views are _not_ dropped.  If I close the connection in Navicat, the error goes away and everything is wiped.

2) This spawn a number of test databases unexpectedly.  Seems to only get up to 7 though.

![image](https://user-images.githubusercontent.com/124717/72865061-4a20b680-3c8b-11ea-82b6-138e14fbf14b.png)

```
# full error output
bundle exec rake
Run options: --seed 8282

# Running:

Traceback (most recent call last):
	20: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
	19: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:138:in `run'
	18: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `start'
	17: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `map'
	16: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `each'
	15: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `times'
	14: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `block in start'
	13: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `fork'
	12: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:95:in `block (2 levels) in start'
	11: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1138:in `method_missing'
	10: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1158:in `with_friend'
	 9: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1139:in `block in method_missing'
	 8: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1227:in `open'
	 7: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1140:in `block (2 levels) in method_missing'
	 6: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1251:in `send_message'
	 5: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:929:in `send_request'
	 4: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:610:in `send_request'
	 3: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:610:in `each'
	 2: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:611:in `block in send_request'
	 1: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:565:in `dump'
/Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:565:in `dump': no _dump_data is defined for class PG::Connection (TypeError)
	25: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
	24: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:138:in `run'
	23: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `start'
	22: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `map'
	21: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `each'
	20: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `times'
	19: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `block in start'
	18: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `fork'
	17: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:95:in `block (2 levels) in start'
	16: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1138:in `method_missing'
	15: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1158:in `with_friend'
	14: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1139:in `block in method_missing'
	13: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1227:in `open'
	12: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1140:in `block (2 levels) in method_missing'
	11: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1251:in `send_message'
	10: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:929:in `send_request'
	 9: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:610:in `send_request'
	 8: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:610:in `each'
	 7: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:611:in `block in send_request'
	 6: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:564:in `dump'
	 5: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:567:in `rescue in dump'
	 4: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:650:in `make_proxy'
	 3: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:650:in `new'
	 2: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1101:in `initialize'
	 1: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1807:in `to_id'
/Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1738:in `current_server': DRb::DRbServerNotFound (DRb::DRbServerNotFound)
	25: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
	24: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:138:in `run'
	23: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `start'
	22: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `map'
	21: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `each'
	20: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `times'
	19: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `block in start'
	18: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `fork'
	17: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:95:in `block (2 levels) in start'
	16: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1138:in `method_missing'
	15: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1158:in `with_friend'
	14: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1139:in `block in method_missing'
	13: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1227:in `open'
	12: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1140:in `block (2 levels) in method_missing'
	11: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1251:in `send_message'
	10: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:929:in `send_request'
	 9: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:610:in `send_request'
	 8: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:610:in `each'
	 7: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:611:in `block in send_request'
	 6: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:564:in `dump'
	 5: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:567:in `rescue in dump'
	 4: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:650:in `make_proxy'
	 3: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:650:in `new'
	 2: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1101:in `initialize'
	 1: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1807:in `to_id'
/Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1738:in `current_server': DRb::DRbServerNotFound (DRb::DRbConnError)
	11: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
	10: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:138:in `run'
	 9: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `start'
	 8: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `map'
	 7: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `each'
	 6: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `times'
	 5: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `block in start'
	 4: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `fork'
	 3: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:94:in `block (2 levels) in start'
	 2: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:97:in `rescue in block (2 levels) in start'
	 1: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:97:in `each'
/Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:98:in `block (3 levels) in start': undefined method `exception=' for #<Minitest::UnexpectedError: Unexpected exception> (NoMethodError)
Did you mean?  exception
F

Failure:
PersonTest#test_there_are_five_seeded_people [/Users/damon/Documents/linguabee/test-app-6/test/models/person_test.rb:12]:
Expected: 5
  Actual: 0


rails test test/models/person_test.rb:11

Traceback (most recent call last):
	2: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
	1: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.14.0/lib/minitest.rb:145:in `run'
/Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:118:in `shutdown': Queue not empty, but all workers have finished. This probably means that a worker crashed and 1 tests were missed. (RuntimeError)
```

### Appreciate your help

Thank you!

### System configuration
**Rails version**: 6.0.2.1 

**Ruby version**: 2.6.3

**Comment by eileencodes** [comment]
Wiping the database at the end of the test suite is a feature of parallel testing, otherwise you could end up with 25 databases leftover. However in 6.1 we stopped wiping the databases so maybe we can backport just that part.

**Comment by thornomad** [comment]
Thanks for your quick response on this.  Let me know if there is anything more you need from me.  I think we will have to put off upgrading a little until a fix gets included though in a bug release or upgrade.  We rely on too many views!  

I can say, though, I am very excited about leveraging the parallel testing!

**Comment by eileencodes** [comment]
I was wrong what the cause of the exception here but it's already been fixed in 6-0-stable by https://github.com/rails/rails/commit/2afc9fd8aee7eac9cb433fcedf4a4750ae4ac995

To continue your upgrade you can either turn off parallel testing, build your gem from 6-0-stable (this is what I'd do), or wait until the next 6.0.x release.

**Comment by thornomad** [comment]
I can confirm that when I update the reference in the example (above) to the `6-0-stable` branch the exception has been fixed!  No more messy errors.  Thanks!

However: **the tests I provided above still do not pass in 6.0.**  (And they pass in in 5.2)

Has there been a permanent change in the expected behavior from 5.2 to 6.0 ?  

Any further help is much appreciated!  Thank you.

PS: I commented out the `parallelize` call in `test/test_helper.rb` on the off chance that would revert to the previous behavior—and while it does stop the parallel business the postgres view is being wiped, as is the data that was seeded during the migration.

#### updated output from 6.0 tests

```
~ bundle exec rake
Run options: --seed 13117

# Running:

E

Error:
PersonTest#test_there_are_five_people_in_the_view:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "view_people" does not exist
LINE 8:  WHERE a.attrelid = '"view_people"'::regclass
                            ^
    test/models/person_test.rb:16:in `block in <class:PersonTest>'

rails test test/models/person_test.rb:15

F

Failure:
PersonTest#test_there_are_five_seeded_people [/Users/damon/Documents/linguabee/test-app-6/test/models/person_test.rb:12]:
Expected: 5
  Actual: 0

rails test test/models/person_test.rb:11

Finished in 0.020401s, 98.0344 runs/s, 49.0172 assertions/s.
2 runs, 1 assertions, 1 failures, 1 errors, 0 skips
```

**Comment by eileencodes** [comment]
Can you provide a demo app? I don't know how to make a "view" in postgres. The other app provided by the other reporter did not demonstrate the issue you're having.

**Comment by thornomad** [comment]
Sure!  I hope this helps (and gets you what you need):

Rails 6: https://github.com/thornomad/issue-38279-rails-6
Rails 5: https://github.com/thornomad/issue-38279-rails-5

PS: the migration example I posted in the original message above creates the view for you when it is first run.  It will get erased in 6.0 when the test runs, so you have to rollback and re-migrate if you want to see it in your database again.

**Comment by BKSpurgeon** [comment]
@eileencodes @thornomad  thank you for your contribution to rails!

@eileencodes am curious how did you go about debugging this particular problem? As I understand it, the following exceptions were thrown, in the following order (i.e. from the top of the stack trace to the bottom): Given that information, how did you proceed?

```shell
1. 1: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:565:in `dump'
/Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:565:in **`dump': no _dump_data is defined for class PG::Connection (TypeError)**

2. 1: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1807:in `to_id'
/Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1738:in `current_server': **DRb::DRbServerNotFound (DRb::DRbServerNotFound)**

3. /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1738:in `current_server': **DRb::DRbServerNotFound (DRb::DRbConnError)**

4. /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:98:in `block (3 levels) in start': undefined method `exception=' for #<Minitest::UnexpectedError: Unexpected exception> **(NoMethodError)**
```

**Comment by eileencodes** [comment]
> am curious how did you go about debugging this particular problem

I checked out your repo, hooked it up to my local copy of Rails. I verified `master` passes, `6-0-stable` also passed so I bisected between the `6-0-stable` branch and the `v6.0.2.1` tag. Since it was already fixed on `6-0-stable` I flipped the good/bad arguments and got to https://github.com/rails/rails/commit/2afc9fd8aee7eac9cb433fcedf4a4750ae4ac995 as the fix. I checked out `v6.0.2.1` and applied just that commit and saw it fixed the issue.

**Comment by thornomad** [comment]
As I look over this thread again, I believe the main issue I am having is different from what @BKSpurgeon originally posted in #38281 and unrelated to the stack trace I originally included (which is resolved in the `6-0-stable` branch).

My main issue is that postgres views and functions are now getting cleared out between test runs (regardless of parallel testing, and also in rspec as an aside).  This is new behavior in the 6 series that wasn't in the 5 series.

@eileencodes : Would it make sense for me to post a new issue that can cleanly focus on this problem (wiping views/functions), without all the unrelated information to the exceptions that were previously being thrown?  I include again the two example repos I created as well.  Let me know.

**Comment by eileencodes** [comment]
Hey @thornomad I checked out the Rails 5 project and the Rails 6 project and it doesn't pass on Rails 5. Are you sure this is passing on 5.2 for you? I think you should open another issue because this is about parallel testing and you have a separate issue not caused by parallel testing and not caused by Rails 6. If you can find a Rails version that exists it will help us find if the issue you're experiencing is a bug.

**Comment by thornomad** [comment]
Interesting.  Yes ... the rails 5 example surely passes for me.  I wonder what is different about our setups.  I asked a colleague of mine to follow these same steps and they had all the tests pass as well for the Rails 5.

```
git clone git@github.com:thornomad/issue-38279-rails-5.git
cd issue-38279-rails-5/
bundle install
bundle exec rake db:create
bundle exec rake db:migrate RAILS_ENV=test
bundle exec rake
```

I will open another issue and see about using Docker or something ... which I have not used before.  I wonder if it has something to do with the postgres version.  Will try and find somone else to test it as well as my colleague and my setups are pretty similar.

![render1579806626266-min](https://user-images.githubusercontent.com/124717/73016332-814daf80-3dd2-11ea-916b-7d89cf5a45d4.gif)

**Comment by BKSpurgeon** [comment]
> > am curious how did you go about debugging this particular problem
> 
> I checked out your repo, hooked it up to my local copy of Rails. I verified `master` passes, `6-0-stable` also passed so I used `git bisect` on the `6-0-stable` branch and the `v6.0.2.1` tag. Since it was already fixed on `6-0-stable` I flipped the good/bad arguments and got to [2afc9fd](https://github.com/rails/rails/commit/2afc9fd8aee7eac9cb433fcedf4a4750ae4ac995) as the fix. I checked out `v6.0.2.1` and applied just that commit and saw it fixed the issue.

Brilliant. Using your instructions I was able to perfectly debug to the very commit that you have found. Hopefully this will enable me to further debug other rails issues.

**Comment by BKSpurgeon** [comment]
> Hey @thornomad I checked out the Rails 5 project and the Rails 6 project and it doesn't pass on Rails 5 either. Are you sure this is passing on 5.2 for you? I think you should open another issue because this issue is about parallel testing and you have a separate issue not caused by parallel testing and not caused by Rails 6. If you can find a Rails version that does not demo the bug, it will help us find if the issue you're experiencing is a bug.

This is very interesting. I too have tested using the following repos:

Rails 6: https://github.com/thornomad/issue-38279-rails-6
Rails 5: https://github.com/thornomad/issue-38279-rails-5

but as with @thornomad  have found that it passes on rails 5, but fails on the rails 6:

```shell
✔ ~/UbuntuHDD/Documents/RailsProjects/issue-38279-rails-6 [master|✔] 
11:06 $ bundle exec rake
Run options: --seed 42633

# Running:

E

Error:
PersonTest#test_there_are_five_people_in_the_view:
DRb::DRbRemoteError: PG::UndefinedTable: ERROR:  relation "view_people" does not exist
LINE 8:  WHERE a.attrelid = '"view_people"'::regclass
                            ^
 (ActiveRecord::StatementInvalid)
    test/models/person_test.rb:16:in `block in <class:PersonTest>'


rails test test/models/person_test.rb:15

F

Failure:
PersonTest#test_there_are_five_seeded_people [/home/koshy/UbuntuHDD/Documents/RailsProjects/issue-38279-rails-6/test/models/person_test.rb:12]:
Expected: 5
  Actual: 0


rails test test/models/person_test.rb:11

```

**Comment by thornomad** [comment]
@BKSpurgeon - thanks so much for taking the time to try this out!  Appreciate it.  

I went ahead and opened a new issue #38302 and updated the repos to include a Dockerfile ... first time trying that, so I hope it works.  Just in case there is something in the specific setup that is not demonstrating the same behavior we are seeing.

**Comment by SampsonCrowley** [comment]
I'm still seeing this on 6.0.2.1

**Comment by SampsonCrowley** [comment]
i can't run a single test with parallelization because it just throws: 
```ruby
1. 1: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:565:in `dump'
/Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:565:in **`dump': no _dump_data is defined for class PG::Connection (TypeError)**

2. 1: from /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1807:in `to_id'
/Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1738:in `current_server': **DRb::DRbServerNotFound (DRb::DRbServerNotFound)**

3. /Users/damon/.rbenv/versions/2.6.3/lib/ruby/2.6.0/drb/drb.rb:1738:in `current_server': **DRb::DRbServerNotFound (DRb::DRbConnError)**

4. /Users/damon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:98:in `block (3 levels) in start': undefined method `exception=' for #<Minitest::UnexpectedError: Unexpected exception> **(NoMethodError)**
```

**Comment by thornomad** [comment]
@SampsonCrowley - are you using the `6-0-stable` branch ?

**Comment by SampsonCrowley** [comment]
@thornomad it turned out to be a fixture containing a database constraint violation. I already opened a separate issue on the error being almost completely useless for the actual causing issue

**Comment by marcosvafilho** [comment]
Same here. Using Rails 6.0.2.1 and getting the following errors:

- DRb::DRbServerNotFound (DRb::DRbConnError)
- undefined method `exception=' for #<Minitest::UnexpectedError: Unexpected exception> (NoMethodError)
- no _dump_data is defined for class PG::Connection

It works fine when commenting out the `parallelize()` method.

**Comment by BKSpurgeon** [comment]
> @thornomad I'm on 6.0.2.1 as mentioned above.
> 
> It turned out to be a fixture containing a database constraint violation. I already opened a separate issue on the error being almost completely unusable for debugging the actual causing issue

Here is the issue for those wanting the link: #38342

**Comment by gilbert** [comment]
Setting `gem 'minitest', '~> 5.13.0'` in my Gemfile is what fixed this for me. Like @SampsonCrowley, the problem was a database constraint violation in a fixture. Switching from minitest 5.14.0 to 5.13.0 does not solve the constraint violation (obviously), but now I can see a useful error message regarding it.

**Comment by curtp** [comment]
We ran into this issue and it ended up being a mysql permission problem. The login for the test database didn't have permission to create new databases and it failed with this error message. Once we granted permission to the account, everything worked.
