### ISSUE TITLE
Ruby 2.7 deprecation warnings in 6.0.3

### ISSUE THREAD

**Issue by morgoth** [rails/rails#39227]
When I run my test suite with Rails 6.0.3 and Ruby 2.7.1 I'm getting deprecation warnings in this places:

```
/home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3/lib/active_record/suppressor.rb:43: warning: The called method `save' is defined here

/home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3/lib/active_support/cache.rb:330: warning: Passing the keyword argument as the last hash parameter is deprecated

/home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3/lib/active_support/cache.rb:710: warning: The called method `get_entry_value' is defined here

/home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3/lib/active_record/relation.rb:412: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

/home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3/lib/action_dispatch/routing/url_for.rb:108: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

I'm not entirely sure if this is caused by internals of Rails or because how it is used in the app, as it's hard to find out just by stacktrace.

**Comment by nedenwalker** [comment]
We have this occurring as well. We upgraded Ruby from 2.6.5 to 2.7.1 and then Rails from 6.0.2.2 to 6.0.3. It is curious that the paths show ruby/2.7.1 and gems/2.7.0, but maybe that is fine? It does seem to be rails internal.

**Comment by nedenwalker** [comment]
Also, to note, we tried `bundle exec rails app:update` after changing the rails version in our Gemfile, but saw that it overwrote much of our custom code, so we backed out of those changes. Perhaps they are critical to this?

**Comment by rafaelfranca** [comment]
No. It is not required to run `rails app:update` to remove the warnings.

**Comment by nedenwalker** [comment]
Actually, it does appear that Rails has been updated and does not show the deprecation warnings. What we are seeing is a mass amount of json-2.2.0 package deprecations, which is different. So, thank you for removing from Rails.

**Comment by jonathanhefner** [comment]
> /home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3/lib/active_record/suppressor.rb:43: warning: The called method `save' is defined here

@morgoth Was there another warning paired with this one that specified where the call site was?

> /home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3/lib/active_support/cache.rb:330: warning: Passing the keyword argument as the last hash parameter is deprecated
> /home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3/lib/active_support/cache.rb:710: warning: The called method `get_entry_value' is defined here

Fixed by 3f27aa8cdf8c3c7f36d630f0241854f712e4c937.

> /home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3/lib/active_record/relation.rb:412: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

Fixed by #39199.

> /home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3/lib/action_dispatch/routing/url_for.rb:108: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

Fixed by #39241.

**Comment by morgoth** [comment]
@jonathanhefner Thank you for looking into this.
> /home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3/lib/active_record/suppressor.rb:43: warning: The called method `save' is defined here

> @morgoth Was there another warning paired with this one that specified where the call site was?

Yes, looks like it is paired with
```
/home/wojtek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/authlogic-6.0.0/lib/authlogic/acts_as_authentic/session_maintenance.rb:98: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```
https://github.com/binarylogic/authlogic/blob/a857ebfbe671bf4c1c63e760ef65183306e4beb4/lib/authlogic/acts_as_authentic/session_maintenance.rb#L98

I guess this should be changed to match the definition of https://github.com/rails/rails/blob/b738f1930f3c82f51741ef7241c1fee691d7deb2/activerecord/lib/active_record/suppressor.rb#L43 ?

**Comment by kamipo** [comment]
Yes, actually `save` doesn't regard positional arguments, so `save_without_session_maintenance(*args)` should be `save_without_session_maintenance(**options)`.

See 57b4668c113b531f0b9a3e271b39aa19b686ab1d.

**Comment by jonathanhefner** [comment]
@rafaelfranca Should these fixes https://github.com/rails/rails/issues/39227#issuecomment-626913910 be backported for 6.0.4?

**Comment by K1N5L4Y3R** [comment]
May I also add the following warning that I'm still seeing after upgrading to Rails 6.0.3:

```
/Users/user/.rvm/gems/ruby-2.7.1@gemset/gems/actionpack-6.0.3/lib/action_dispatch/testing/integration.rb:352: warning: The called method is defined here
```

**Comment by jonathanhefner** [comment]
> `/Users/user/.rvm/gems/ruby-2.7.1@gemset/gems/actionpack-6.0.3/lib/action_dispatch/testing/integration.rb:352: warning: The called method is defined here`

I believe this is fixed by 1dac170c236a4ba30ffad9b8d648bcc396e9c78a.

**Comment by kamipo** [comment]
> May I also add the following warning that I'm still seeing after upgrading to Rails 6.0.3:
>
> ```
> /Users/user/.rvm/gems/ruby-2.7.1@gemset/gems/actionpack-6.0.3/lib/action_dispatch/testing/integration.rb:352: warning: The called method is defined here
> ```

Can you share the call site warning?
It should be fixed by the call site like #716.

**Comment by denisj** [comment]
Hello, I still got these warnings after updating to 6.0.3.1

`/gems/ruby/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/querying.rb:21: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`
`/gems/ruby/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/relation/batches.rb:126: warning: The called method 'find_in_batches' is defined here`

**Comment by jonathanhefner** [comment]
@denisj If I'm not mistaken, that warning is actually caused by your code.  It's tricky, but the warning only appears to be from `lib/active_record/querying.rb:21` because of the way methods are delegated.

Do you have any calls to `find_in_batches` in your code where you are passing a Hash without a `**`?

**Comment by denisj** [comment]
My bad, @jonathanhefner. The warning cames from the elasticsearch-rails gem. I saw that they fixed it, but not yet released it yet. Thank you.

**Comment by jonathanhefner** [comment]
Since all of [these warning fixes](https://github.com/rails/rails/issues/39227#issuecomment-626913910) have been backported, I'm going to close this issue.

* 3f27aa8cdf8c3c7f36d630f0241854f712e4c937 - Backported to `6-0-stable` in c0fd8f4bb2d4dd9abfbef9cc658ca0c88b8b0842
* #39199 / 47779e75b97e669897c5c437734d74e0a0b86f4d - Backported to `6-0-stable` in ec830e0cf3b6995f2bca1a90d4cbfe7160f30e42
* #39241 / 1ecd39d8bd876af702e16c860ff8b71bb43c00bb - Backported to `6-0-stable` in 04d0fa7e5f210ca49b758f4678d0fe3d3da4d7b5

If you encounter new warnings, please open a new issue!
