### ISSUE TITLE
No such file or directory - /usr/src/app/bin/yarn

### ISSUE THREAD

**Issue by stefanahman** [rails/rails#40795]
### Steps to reproduce
When I run `bin/rails assets:precompile` I get a `Errno::ENOENT` exception. Probably related to https://github.com/rails/rails/pull/40739.

### Expected behavior
I expect the precompilation of assets to fallback to existing yarn when not found in `bin` directory.

### Actual behavior
```
RUN RAILS_ENV=production bin/rails assets:precompile
rails aborted!
Errno::ENOENT: No such file or directory - /usr/src/app/bin/yarn
 
Tasks: TOP => assets:precompile => yarn:install
```

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.2

**Comment by doits** [comment]
Looks like `bin/yarn` is not present in your system, but it should be if you want to use javascript.

Try to run `bundle exec rails app:update:bin`. Does this create `bin/yarn`? (This should have been done by `rails app:update` beginning from 5.1 or 5.2 I think).

**Comment by mvz** [comment]
If you run `rails new --skip-javascript` to create a Rails application, `yarn:install` will still be run when running `assets:precompile`.

**Comment by mvz** [comment]
Running `undle exec rails app:update:bin` gives:
```
       exist  bin
   identical  bin/rails
   identical  bin/rake
   identical  bin/setup
      create  bin/spring
      create  bin/yarn
      remove  bin/spring
      remove  bin/yarn
```

This is in a fresh Rails 6.1 application created with `rails new --skip-bundle --skip-test-unit --skip-spring --skip-bootsnap --skip-listen --skip-javascript --skip-webpack-install`.

**Comment by edariedl** [comment]
We are still using sprockets to compile javascripts and we are getting the same error. It is caused by this change https://github.com/rails/rails/pull/40722 (https://github.com/rails/rails/commit/b087511bc49097a6dc2afe0256bb6d39ebb3a4ab)

full stack trace:
```
[project#rails-6-1]→ rails assets:precompile --trace 
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke yarn:install (first_time)
** Execute yarn:install
rails aborted!
Errno::ENOENT: No such file or directory - /project_path/bin/yarn
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/tasks/yarn.rake:13:in ``'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/tasks/yarn.rake:13:in `block (2 levels) in <main>'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_module.rb:59:in `with_application'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/command.rb:52:in `invoke'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0/lib/rails/commands.rb:18:in `<main>'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
/project_path/bin/rails:8:in `<top (required)>'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/edariedl/.rbenv/versions/2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/project_path/bin/spring:16:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => assets:precompile => yarn:install
```

`system` call swallows the problem and returns `nil` if command doesn't exist. Backgticks `` on the other hand raises an exception. That is the reason it is raising exceptions.

It worked fine in 6.1.0.rc2, it was broken by final release.

**Comment by edariedl** [comment]
running `bundle exec rails app:update:bin --trace` gives me pretty much the same output as @mvz above:
```
** Invoke app:update:bin (first_time)
** Execute app:update:bin
       exist  bin
   identical  bin/rails
   identical  bin/rake
   identical  bin/setup
   identical  bin/spring
      create  bin/yarn
      remove  bin/yarn
```

**Comment by doits** [comment]
Allright, thanks for trying it out. It looks like the problem in the end lies in those lines then:

https://github.com/rails/rails/blob/6-1-stable/railties/lib/rails/tasks/yarn.rake#L23-L26

It *always* runs the task on precompiling assets, even though it seems it shouldn't because you skipped javascript. That is why it removes `bin/yarn` on your setup on `rails app:update:bin`. But it still tries to call it by running `yarn:install`.

Before https://github.com/rails/rails/commit/b087511bc49097a6dc2afe0256bb6d39ebb3a4ab, the task would fail *silently*. It still was a bug that it was run at all but it did no harm. Now it breaks the pipeline.

I already have PR #40785 ready and will change it so that if the task fails it will at least continue with everything else like before.

To fix it properly something must be done with the lines I quoted above – maybe they should even be removed completely so `yarn:install` is never run automatically (just like `bundle install` has to be done manually, too). At least it should only be run when it should, e.g. when javascript is enabled in this project. Anyways, this is something for the Rails team to decide.

**Comment by doits** [comment]
I updated #40785 to only run `yarn:install` on `assets:precompile` if `bin/yarn` is present (which seems to be the way to check if the project was created with `--skip-javascript` or not).

Can you please try it out @mvz, @edariedl and report back if this fixes it for you?

**Comment by edariedl** [comment]
@doits  Looks like it fixes it for us 👍, thanks, hopefully it gets merged soon.

**Comment by mvz** [comment]
@doits I can confirm that this fixes things for my case as well. Thanks!

**Comment by mukinabis** [comment]
What temporary solution is suitable? I really need version 6.1, but because of this problem, I can't update.

**Comment by doits** [comment]
@mukinabis see https://github.com/barsoom/pipeline/commit/3906724b34b4803d815f9ab1252b6046d00b8821 where the rake task is overwritten to do nothing

**Comment by alexander-alyoshin** [comment]
@doits see https://github.com/barsoom/pipeline/blob/f1741e83a7276b30a008b7918c9f0dec048a4e55/bin/yarn

**Comment by KevinBongart** [comment]
@rafaelfranca Do you have a minute to explain the rationale behind closing this issue? As far as I understand, `yarn` is now a required dependency for Rails 6.1.0 apps so that `rails assets:precompile` work, even if there is nothing for `yarn` to install. Before Rails 6.1.0, `rails assets:precompile` worked fine without `yarn` installed on a system as `rake yarn:install` failed silently.

**Comment by edariedl** [comment]
@KevinBongart fix was merged https://github.com/rails/rails/pull/40785, no need for open issue anymore.

**Comment by samstickland** [comment]
Any idea what is happening here.. this is a project I have upgraded to Rails 6.1, but when I run `rails app:update:bin``yarn` is being installed and then removed:

```
 bundle exec rails app:update:bin
       exist  bin
   identical  bin/rails
   identical  bin/rake
   identical  bin/setup
      create  bin/spring
      create  bin/yarn
      remove  bin/spring
      remove  bin/yarn
```

The project is using webpacker.

**Comment by samstickland** [comment]
Ah, ignore my question.. It is a duplicate of: https://github.com/rails/rails/issues/40868

**Comment by AnthonyFrancis** [comment]
HEY! Has this fix been pushed to the main branch yet? Just installed rails 6.1.0 and still having the same issue.

**Comment by espen** [comment]
@AnthonyFrancis no new version is released but it is included in [6-1-stable](https://github.com/rails/rails/tree/6-1-stable)

**Comment by dhh** [comment]
As a temporary fix, you can add the following to your Rakefile:

```ruby
Rake::Task["yarn:install"].clear

namespace :yarn do
  task :install do
    # Do nothing, since there's no yarn
  end
end
```

**Comment by KevinBongart** [comment]
@AnthonyFrancis looks like Rails 6.1.1 was just released and it includes the fix for `yarn:install`

**Comment by maxence33** [comment]
Hi, 
Sorry to dig this issue especially if it has been fixed for everyone else. 
I am in process of updating an app from 5.2 Sprockets to 6.1.5 and decided to skip webpacker which is now deprecated in favor of jsbundling-rails

Then installed jsbundling-rails with rollup which created appropriate folders `assets/builds` `javascript` etc .. 
`rails app:update` still creates and removes `bin/yarn` whether on Rails 6.1.1 or 6.1.5

Not too sure why this happen as I am indeed using javascript here .. though I agree may have kinda mixed up steps in upgrading .. 

npm 6.14.15
yarn 1.22.5
node 14.17.6

**Comment by maxence33** [comment]
My apologies. probably no issue with yarn file missing. Didn't set the build script correctly in package.json. Seems all fine.
