### ISSUE TITLE
Failsafe expectations of `RedisCacheStore`?

### ISSUE THREAD

**Issue by booleanbetrayal** [rails/rails#42818]
### Steps to reproduce

1. Reboot a Redis cluster while pointing a `RedisCacheStore` to it.
2. Observe`Redis::CannotConnectError` and likely downtime the moment a new Redis cache connection needs to be established during the reboot event. eg: 
```
Redis::CannotConnectError: Error connecting to Redis on some-redis-host.com:6379 (Errno::ECONNREFUSED)
  from redis (4.3.1) lib/redis/client.rb:382:in `rescue in establish_connection'
```

### Expected behavior

The `RedisCacheStore` documentation [states](https://api.rubyonrails.org/classes/ActiveSupport/Cache/RedisCacheStore.html): 

>Fault tolerant. If the Redis server is unavailable, no exceptions are raised. Cache fetches are all misses and writes are dropped.

Based on this guidance, we would assume connect attempt errors were transparently handled in a way that would not be end-user noticable.

### Actual behavior
We see the connection errors stemming from the Redis client during operational events that propagate into downtime for our application. We have tried the standard driver as well as `hiredis` and both behave in the same fashion. Quickly reviewing the [source](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/redis_cache_store.rb) and the use of `failsafe` it appears that this may be too low-level for the cache store to address. 

Is this the case, and should documentation be clarified, or is this a legitimate bug / environmental configuration issue?

### System configuration
**Rails version**:
6.1.3.2

**Ruby version**:
2.7.4 - Alpine Linux 3.14

**Comment by ghiculescu** [comment]
```
2.7.3 :001 > Redis::CannotConnectError
 => Redis::CannotConnectError
2.7.3 :002 > Redis::CannotConnectError.superclass
 => Redis::BaseConnectionError
2.7.3 :003 > Redis::CannotConnectError.superclass.superclass
 => Redis::BaseError
```

This suggests that those errors should be getting caught

https://github.com/rails/rails/blob/6442aac195a227455c53c5b5b00c6818268379e5/activesupport/lib/active_support/cache/redis_cache_store.rb#L486

Do you have a backtrace so we can confirm if the error you're getting is going through the `failsafe`?

**Comment by booleanbetrayal** [comment]
@ghiculescu  - Here is a set of (sanitized) backtraces we are seeing in Sentry, stemming from a DelayedJob failure:

```
Errno::ETIMEDOUT: Operation timed out
  from redis (4.3.1) lib/redis/connection/hiredis.rb:20:in `connect'
  from redis (4.3.1) lib/redis/connection/hiredis.rb:20:in `connect'
  from redis (4.3.1) lib/redis/client.rb:369:in `establish_connection'
  from redis (4.3.1) lib/redis/client.rb:117:in `block in connect'
  from redis (4.3.1) lib/redis/client.rb:328:in `with_reconnect'
  from redis (4.3.1) lib/redis/client.rb:116:in `connect'
  from redis (4.3.1) lib/redis/client.rb:401:in `ensure_connected'
  from redis (4.3.1) lib/redis/client.rb:253:in `block in process'
  from redis (4.3.1) lib/redis/client.rb:340:in `logging'
  from redis (4.3.1) lib/redis/client.rb:252:in `process'
  from redis (4.3.1) lib/redis/client.rb:146:in `call'
  from prometheus_exporter (767b6a4e00f5) lib/prometheus_exporter/instrumentation/method_profiler.rb:15:in `call'
  from redis (4.3.1) lib/redis.rb:956:in `block in get'
  from redis (4.3.1) lib/redis.rb:70:in `block in synchronize'
  from monitor.rb:202:in `synchronize'
  from monitor.rb:202:in `mon_synchronize'
  from redis (4.3.1) lib/redis.rb:70:in `synchronize'
  from redis (4.3.1) lib/redis.rb:955:in `get'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:349:in `block (2 levels) in read_entry'
  from connection_pool (2.2.5) lib/connection_pool.rb:63:in `block (2 levels) in with'
  from connection_pool (2.2.5) lib/connection_pool.rb:62:in `handle_interrupt'
  from connection_pool (2.2.5) lib/connection_pool.rb:62:in `block in with'
  from connection_pool (2.2.5) lib/connection_pool.rb:59:in `handle_interrupt'
  from connection_pool (2.2.5) lib/connection_pool.rb:59:in `with'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:349:in `block in read_entry'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:478:in `failsafe'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:347:in `read_entry'
  from activesupport (6.1.3.2) lib/active_support/cache/strategy/local_cache.rb:141:in `read_entry'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:327:in `block in fetch'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:720:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:720:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:326:in `fetch'
  from app/models/some_app_code:42:in `some_meth'
  from activejob (6.1.3.2) lib/active_job/execution.rb:48:in `block in perform_now'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  from sentry-rails (4.5.1) lib/sentry/rails/active_job.rb:9:in `block (2 levels) in included'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from marginalia (1.10.1) lib/marginalia/railtie.rb:37:in `block (2 levels) in insert_into_active_job'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from i18n (1.8.10) lib/i18n.rb:314:in `with_locale'
  from activejob (6.1.3.2) lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.3.2) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
  from activejob (6.1.3.2) lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activejob (6.1.3.2) lib/active_job/instrumentation.rb:21:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `instrument'
  from activejob (6.1.3.2) lib/active_job/instrumentation.rb:31:in `instrument'
  from activejob (6.1.3.2) lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activejob (6.1.3.2) lib/active_job/logging.rb:24:in `tag_logger'
  from activejob (6.1.3.2) lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:137:in `run_callbacks'
  from activejob (6.1.3.2) lib/active_job/execution.rb:47:in `perform_now'
  from activejob (6.1.3.2) lib/active_job/execution.rb:25:in `block in execute'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  from activejob (6.1.3.2) lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:71:in `wrap'
  from activejob (6.1.3.2) lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:137:in `run_callbacks'
  from activejob (6.1.3.2) lib/active_job/execution.rb:23:in `execute'
  from activejob (6.1.3.2) lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:91:in `block in perform'
  from skylight (5.1.1) lib/skylight/instrumenter.rb:267:in `instrument'
  from skylight (5.1.1) lib/skylight.rb:200:in `instrument'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:91:in `perform'
  from delayed_job (4.1.9) lib/delayed/backend/base.rb:81:in `block in invoke_job'
  from config/initializers/delayed_job.rb:114:in `block (2 levels) in <class:PrometheusPlugin>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from sentry-delayed_job (4.5.1) lib/sentry/delayed_job/plugin.rb:20:in `block (3 levels) in <class:Plugin>'
  from sentry-ruby-core (4.5.1) lib/sentry/hub.rb:56:in `with_scope'
  from sentry-ruby-core (4.5.1) lib/sentry-ruby.rb:167:in `with_scope'
  from sentry-delayed_job (4.5.1) lib/sentry/delayed_job/plugin.rb:15:in `block (2 levels) in <class:Plugin>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/backend/base.rb:78:in `invoke_job'
  from delayed_job (4.1.9) lib/delayed/worker.rb:230:in `block (2 levels) in run'
  from timeout.rb:95:in `block in timeout'
  from timeout.rb:105:in `timeout'
  from delayed_job (4.1.9) lib/delayed/worker.rb:230:in `block in run'
  from benchmark.rb:308:in `realtime'
  from delayed_job (4.1.9) lib/delayed/worker.rb:229:in `run'
  from delayed_job (4.1.9) lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:35:in `block in sk_instrument'
  from skylight (5.1.1) lib/skylight.rb:150:in `block in trace'
  from skylight (5.1.1) lib/skylight/instrumenter.rb:224:in `trace'
  from skylight (5.1.1) lib/skylight.rb:149:in `trace'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:24:in `sk_instrument'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:13:in `block (2 levels) in <class:Plugin>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
  from delayed_job (4.1.9) lib/delayed/worker.rb:213:in `block in work_off'
  from delayed_job (4.1.9) lib/delayed/worker.rb:212:in `times'
  from delayed_job (4.1.9) lib/delayed/worker.rb:212:in `work_off'
  from delayed_job (4.1.9) lib/delayed/worker.rb:175:in `block (4 levels) in start'
  from benchmark.rb:308:in `realtime'
  from delayed_job (4.1.9) lib/delayed/worker.rb:174:in `block (3 levels) in start'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/worker.rb:173:in `block (2 levels) in start'
  from delayed_job (4.1.9) lib/delayed/worker.rb:172:in `loop'
  from delayed_job (4.1.9) lib/delayed/worker.rb:172:in `block in start'
  from delayed_job (4.1.9) lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/worker.rb:171:in `start'
  from delayed_job (4.1.9) lib/delayed/command.rb:137:in `run'
  from delayed_job (4.1.9) lib/delayed/command.rb:125:in `block in run_process'
  from daemons (1.4.0) lib/daemons/application.rb:277:in `block in start_proc'
  from daemons (1.4.0) lib/daemons/application.rb:286:in `start_proc'
  from daemons (1.4.0) lib/daemons/application.rb:307:in `start'
  from daemons (1.4.0) lib/daemons/controller.rb:59:in `run'
  from daemons (1.4.0) lib/daemons.rb:199:in `block in run_proc'
  from daemons (1.4.0) lib/daemons/cmdline.rb:124:in `catch_exceptions'
  from daemons (1.4.0) lib/daemons.rb:198:in `run_proc'
  from delayed_job (4.1.9) lib/delayed/command.rb:123:in `run_process'
  from delayed_job (4.1.9) lib/delayed/command.rb:104:in `block in daemonize'
  from delayed_job (4.1.9) lib/delayed/command.rb:102:in `times'
  from delayed_job (4.1.9) lib/delayed/command.rb:102:in `daemonize'
  from bin/delayed_job:5:in `<main>'

Redis::TimeoutError: Redis::TimeoutError
  from redis (4.3.1) lib/redis/connection/hiredis.rb:27:in `rescue in connect'
  from redis (4.3.1) lib/redis/connection/hiredis.rb:11:in `connect'
  from redis (4.3.1) lib/redis/client.rb:369:in `establish_connection'
  from redis (4.3.1) lib/redis/client.rb:117:in `block in connect'
  from redis (4.3.1) lib/redis/client.rb:328:in `with_reconnect'
  from redis (4.3.1) lib/redis/client.rb:116:in `connect'
  from redis (4.3.1) lib/redis/client.rb:401:in `ensure_connected'
  from redis (4.3.1) lib/redis/client.rb:253:in `block in process'
  from redis (4.3.1) lib/redis/client.rb:340:in `logging'
  from redis (4.3.1) lib/redis/client.rb:252:in `process'
  from redis (4.3.1) lib/redis/client.rb:146:in `call'
  from prometheus_exporter (767b6a4e00f5) lib/prometheus_exporter/instrumentation/method_profiler.rb:15:in `call'
  from redis (4.3.1) lib/redis.rb:956:in `block in get'
  from redis (4.3.1) lib/redis.rb:70:in `block in synchronize'
  from monitor.rb:202:in `synchronize'
  from monitor.rb:202:in `mon_synchronize'
  from redis (4.3.1) lib/redis.rb:70:in `synchronize'
  from redis (4.3.1) lib/redis.rb:955:in `get'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:349:in `block (2 levels) in read_entry'
  from connection_pool (2.2.5) lib/connection_pool.rb:63:in `block (2 levels) in with'
  from connection_pool (2.2.5) lib/connection_pool.rb:62:in `handle_interrupt'
  from connection_pool (2.2.5) lib/connection_pool.rb:62:in `block in with'
  from connection_pool (2.2.5) lib/connection_pool.rb:59:in `handle_interrupt'
  from connection_pool (2.2.5) lib/connection_pool.rb:59:in `with'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:349:in `block in read_entry'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:478:in `failsafe'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:347:in `read_entry'
  from activesupport (6.1.3.2) lib/active_support/cache/strategy/local_cache.rb:141:in `read_entry'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:327:in `block in fetch'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:720:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:720:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:326:in `fetch'
  from app/models/some_app_code:42:in `some_meth'
  from activejob (6.1.3.2) lib/active_job/execution.rb:48:in `block in perform_now'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  from sentry-rails (4.5.1) lib/sentry/rails/active_job.rb:9:in `block (2 levels) in included'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from marginalia (1.10.1) lib/marginalia/railtie.rb:37:in `block (2 levels) in insert_into_active_job'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from i18n (1.8.10) lib/i18n.rb:314:in `with_locale'
  from activejob (6.1.3.2) lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.3.2) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
  from activejob (6.1.3.2) lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activejob (6.1.3.2) lib/active_job/instrumentation.rb:21:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `instrument'
  from activejob (6.1.3.2) lib/active_job/instrumentation.rb:31:in `instrument'
  from activejob (6.1.3.2) lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activejob (6.1.3.2) lib/active_job/logging.rb:24:in `tag_logger'
  from activejob (6.1.3.2) lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:137:in `run_callbacks'
  from activejob (6.1.3.2) lib/active_job/execution.rb:47:in `perform_now'
  from activejob (6.1.3.2) lib/active_job/execution.rb:25:in `block in execute'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  from activejob (6.1.3.2) lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:71:in `wrap'
  from activejob (6.1.3.2) lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:137:in `run_callbacks'
  from activejob (6.1.3.2) lib/active_job/execution.rb:23:in `execute'
  from activejob (6.1.3.2) lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:91:in `block in perform'
  from skylight (5.1.1) lib/skylight/instrumenter.rb:267:in `instrument'
  from skylight (5.1.1) lib/skylight.rb:200:in `instrument'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:91:in `perform'
  from delayed_job (4.1.9) lib/delayed/backend/base.rb:81:in `block in invoke_job'
  from config/initializers/delayed_job.rb:114:in `block (2 levels) in <class:PrometheusPlugin>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from sentry-delayed_job (4.5.1) lib/sentry/delayed_job/plugin.rb:20:in `block (3 levels) in <class:Plugin>'
  from sentry-ruby-core (4.5.1) lib/sentry/hub.rb:56:in `with_scope'
  from sentry-ruby-core (4.5.1) lib/sentry-ruby.rb:167:in `with_scope'
  from sentry-delayed_job (4.5.1) lib/sentry/delayed_job/plugin.rb:15:in `block (2 levels) in <class:Plugin>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/backend/base.rb:78:in `invoke_job'
  from delayed_job (4.1.9) lib/delayed/worker.rb:230:in `block (2 levels) in run'
  from timeout.rb:95:in `block in timeout'
  from timeout.rb:105:in `timeout'
  from delayed_job (4.1.9) lib/delayed/worker.rb:230:in `block in run'
  from benchmark.rb:308:in `realtime'
  from delayed_job (4.1.9) lib/delayed/worker.rb:229:in `run'
  from delayed_job (4.1.9) lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:35:in `block in sk_instrument'
  from skylight (5.1.1) lib/skylight.rb:150:in `block in trace'
  from skylight (5.1.1) lib/skylight/instrumenter.rb:224:in `trace'
  from skylight (5.1.1) lib/skylight.rb:149:in `trace'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:24:in `sk_instrument'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:13:in `block (2 levels) in <class:Plugin>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
  from delayed_job (4.1.9) lib/delayed/worker.rb:213:in `block in work_off'
  from delayed_job (4.1.9) lib/delayed/worker.rb:212:in `times'
  from delayed_job (4.1.9) lib/delayed/worker.rb:212:in `work_off'
  from delayed_job (4.1.9) lib/delayed/worker.rb:175:in `block (4 levels) in start'
  from benchmark.rb:308:in `realtime'
  from delayed_job (4.1.9) lib/delayed/worker.rb:174:in `block (3 levels) in start'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/worker.rb:173:in `block (2 levels) in start'
  from delayed_job (4.1.9) lib/delayed/worker.rb:172:in `loop'
  from delayed_job (4.1.9) lib/delayed/worker.rb:172:in `block in start'
  from delayed_job (4.1.9) lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/worker.rb:171:in `start'
  from delayed_job (4.1.9) lib/delayed/command.rb:137:in `run'
  from delayed_job (4.1.9) lib/delayed/command.rb:125:in `block in run_process'
  from daemons (1.4.0) lib/daemons/application.rb:277:in `block in start_proc'
  from daemons (1.4.0) lib/daemons/application.rb:286:in `start_proc'
  from daemons (1.4.0) lib/daemons/application.rb:307:in `start'
  from daemons (1.4.0) lib/daemons/controller.rb:59:in `run'
  from daemons (1.4.0) lib/daemons.rb:199:in `block in run_proc'
  from daemons (1.4.0) lib/daemons/cmdline.rb:124:in `catch_exceptions'
  from daemons (1.4.0) lib/daemons.rb:198:in `run_proc'
  from delayed_job (4.1.9) lib/delayed/command.rb:123:in `run_process'
  from delayed_job (4.1.9) lib/delayed/command.rb:104:in `block in daemonize'
  from delayed_job (4.1.9) lib/delayed/command.rb:102:in `times'
  from delayed_job (4.1.9) lib/delayed/command.rb:102:in `daemonize'
  from bin/delayed_job:5:in `<main>'

Redis::CannotConnectError: Error connecting to Redis on some-redis-host:6379 (Redis::TimeoutError)
  from redis (4.3.1) lib/redis/client.rb:382:in `rescue in establish_connection'
  from redis (4.3.1) lib/redis/client.rb:363:in `establish_connection'
  from redis (4.3.1) lib/redis/client.rb:117:in `block in connect'
  from redis (4.3.1) lib/redis/client.rb:328:in `with_reconnect'
  from redis (4.3.1) lib/redis/client.rb:116:in `connect'
  from redis (4.3.1) lib/redis/client.rb:401:in `ensure_connected'
  from redis (4.3.1) lib/redis/client.rb:253:in `block in process'
  from redis (4.3.1) lib/redis/client.rb:340:in `logging'
  from redis (4.3.1) lib/redis/client.rb:252:in `process'
  from redis (4.3.1) lib/redis/client.rb:146:in `call'
  from prometheus_exporter (767b6a4e00f5) lib/prometheus_exporter/instrumentation/method_profiler.rb:15:in `call'
  from redis (4.3.1) lib/redis.rb:956:in `block in get'
  from redis (4.3.1) lib/redis.rb:70:in `block in synchronize'
  from monitor.rb:202:in `synchronize'
  from monitor.rb:202:in `mon_synchronize'
  from redis (4.3.1) lib/redis.rb:70:in `synchronize'
  from redis (4.3.1) lib/redis.rb:955:in `get'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:349:in `block (2 levels) in read_entry'
  from connection_pool (2.2.5) lib/connection_pool.rb:63:in `block (2 levels) in with'
  from connection_pool (2.2.5) lib/connection_pool.rb:62:in `handle_interrupt'
  from connection_pool (2.2.5) lib/connection_pool.rb:62:in `block in with'
  from connection_pool (2.2.5) lib/connection_pool.rb:59:in `handle_interrupt'
  from connection_pool (2.2.5) lib/connection_pool.rb:59:in `with'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:349:in `block in read_entry'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:478:in `failsafe'
  from activesupport (6.1.3.2) lib/active_support/cache/redis_cache_store.rb:347:in `read_entry'
  from activesupport (6.1.3.2) lib/active_support/cache/strategy/local_cache.rb:141:in `read_entry'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:327:in `block in fetch'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:720:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:720:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/cache.rb:326:in `fetch'
  from app/models/some_app_code:42:in `some_meth'
  from activejob (6.1.3.2) lib/active_job/execution.rb:48:in `block in perform_now'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  from sentry-rails (4.5.1) lib/sentry/rails/active_job.rb:9:in `block (2 levels) in included'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from marginalia (1.10.1) lib/marginalia/railtie.rb:37:in `block (2 levels) in insert_into_active_job'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from i18n (1.8.10) lib/i18n.rb:314:in `with_locale'
  from activejob (6.1.3.2) lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.3.2) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
  from activejob (6.1.3.2) lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activejob (6.1.3.2) lib/active_job/instrumentation.rb:21:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `block in instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `instrument'
  from activejob (6.1.3.2) lib/active_job/instrumentation.rb:31:in `instrument'
  from activejob (6.1.3.2) lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activejob (6.1.3.2) lib/active_job/logging.rb:24:in `tag_logger'
  from activejob (6.1.3.2) lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:137:in `run_callbacks'
  from activejob (6.1.3.2) lib/active_job/execution.rb:47:in `perform_now'
  from activejob (6.1.3.2) lib/active_job/execution.rb:25:in `block in execute'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  from activejob (6.1.3.2) lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:71:in `wrap'
  from activejob (6.1.3.2) lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.3.2) lib/active_support/callbacks.rb:137:in `run_callbacks'
  from activejob (6.1.3.2) lib/active_job/execution.rb:23:in `execute'
  from activejob (6.1.3.2) lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:91:in `block in perform'
  from skylight (5.1.1) lib/skylight/instrumenter.rb:267:in `instrument'
  from skylight (5.1.1) lib/skylight.rb:200:in `instrument'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:91:in `perform'
  from delayed_job (4.1.9) lib/delayed/backend/base.rb:81:in `block in invoke_job'
  from config/initializers/delayed_job.rb:114:in `block (2 levels) in <class:PrometheusPlugin>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from sentry-delayed_job (4.5.1) lib/sentry/delayed_job/plugin.rb:20:in `block (3 levels) in <class:Plugin>'
  from sentry-ruby-core (4.5.1) lib/sentry/hub.rb:56:in `with_scope'
  from sentry-ruby-core (4.5.1) lib/sentry-ruby.rb:167:in `with_scope'
  from sentry-delayed_job (4.5.1) lib/sentry/delayed_job/plugin.rb:15:in `block (2 levels) in <class:Plugin>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/backend/base.rb:78:in `invoke_job'
  from delayed_job (4.1.9) lib/delayed/worker.rb:230:in `block (2 levels) in run'
  from timeout.rb:95:in `block in timeout'
  from timeout.rb:105:in `timeout'
  from delayed_job (4.1.9) lib/delayed/worker.rb:230:in `block in run'
  from benchmark.rb:308:in `realtime'
  from delayed_job (4.1.9) lib/delayed/worker.rb:229:in `run'
  from delayed_job (4.1.9) lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:35:in `block in sk_instrument'
  from skylight (5.1.1) lib/skylight.rb:150:in `block in trace'
  from skylight (5.1.1) lib/skylight/instrumenter.rb:224:in `trace'
  from skylight (5.1.1) lib/skylight.rb:149:in `trace'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:24:in `sk_instrument'
  from skylight (5.1.1) lib/skylight/probes/delayed_job.rb:13:in `block (2 levels) in <class:Plugin>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
  from delayed_job (4.1.9) lib/delayed/worker.rb:213:in `block in work_off'
  from delayed_job (4.1.9) lib/delayed/worker.rb:212:in `times'
  from delayed_job (4.1.9) lib/delayed/worker.rb:212:in `work_off'
  from delayed_job (4.1.9) lib/delayed/worker.rb:175:in `block (4 levels) in start'
  from benchmark.rb:308:in `realtime'
  from delayed_job (4.1.9) lib/delayed/worker.rb:174:in `block (3 levels) in start'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/worker.rb:173:in `block (2 levels) in start'
  from delayed_job (4.1.9) lib/delayed/worker.rb:172:in `loop'
  from delayed_job (4.1.9) lib/delayed/worker.rb:172:in `block in start'
  from delayed_job (4.1.9) lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:61:in `block in initialize'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:79:in `block in add'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:66:in `execute'
  from delayed_job (4.1.9) lib/delayed/lifecycle.rb:40:in `run_callbacks'
  from delayed_job (4.1.9) lib/delayed/worker.rb:171:in `start'
  from delayed_job (4.1.9) lib/delayed/command.rb:137:in `run'
  from delayed_job (4.1.9) lib/delayed/command.rb:125:in `block in run_process'
  from daemons (1.4.0) lib/daemons/application.rb:277:in `block in start_proc'
  from daemons (1.4.0) lib/daemons/application.rb:286:in `start_proc'
  from daemons (1.4.0) lib/daemons/application.rb:307:in `start'
  from daemons (1.4.0) lib/daemons/controller.rb:59:in `run'
  from daemons (1.4.0) lib/daemons.rb:199:in `block in run_proc'
  from daemons (1.4.0) lib/daemons/cmdline.rb:124:in `catch_exceptions'
  from daemons (1.4.0) lib/daemons.rb:198:in `run_proc'
  from delayed_job (4.1.9) lib/delayed/command.rb:123:in `run_process'
  from delayed_job (4.1.9) lib/delayed/command.rb:104:in `block in daemonize'
  from delayed_job (4.1.9) lib/delayed/command.rb:102:in `times'
  from delayed_job (4.1.9) lib/delayed/command.rb:102:in `daemonize'
  from bin/delayed_job:5:in `<main>'
```

**Comment by ghiculescu** [comment]
Hmmmm, it seems like the issue is that the error is a `Errno::ETIMEDOUT` (maybe from [here](https://github.com/redis/hiredis-rb/blob/5f0eb41b8fac37fee94cfbe3af482b904c82e48e/lib/hiredis/ruby/connection.rb#L158)), and that is wrapping the Redis errors. So the rescue statement in Rails isn't catching it?

**Comment by ghiculescu** [comment]
Is there any chance you're using a different error handler to the default? https://github.com/rails/rails/blob/75ac626c4e21129d8296d4206a1960563cc3d4aa/activesupport/lib/active_support/cache/redis_cache_store.rb#L59

I can't see any other reason why this would raise. You could verify this by adding a debugger or puts statement in [here](https://github.com/rails/rails/blob/75ac626c4e21129d8296d4206a1960563cc3d4aa/activesupport/lib/active_support/cache/redis_cache_store.rb#L484) and replicating the issue.

**Comment by booleanbetrayal** [comment]
We are using a custom error handler. Here's how we have configured our cache @ghiculescu -

```
config.cache_store = :redis_cache_store, {
    driver: :hiredis,
    url: "redis://some-redis-host.com:6379",
    pool_size: 1,
    connect_timeout: 30,
    pool_timeout: 10,
    read_timeout: 0.5,
    write_timeout: 0.5,
    reconnect_attempts: 1,
    error_handler: -> (method:, returning:, exception:) {
        Sentry.capture_exception exception, level: 'warning', tags: { method: method, returning: returning }
    }
  }
```

**Comment by ghiculescu** [comment]
Ahhh, there's the issue. The error is being manually reported to Sentry. But I think it's being swallowed and the job is continuing regardless. Can you confirm if that's happening or if the jobs are actually failing?

**Comment by booleanbetrayal** [comment]
We were seeing the job error as well as controller requests through our web stack fail during the outage blip, unfortunately.

**Comment by ghiculescu** [comment]
Hmmm okay. I don't really have any other ideas apart from this: 

> You could verify this by adding a debugger or puts statement in [here](https://github.com/rails/rails/blob/75ac626c4e21129d8296d4206a1960563cc3d4aa/activesupport/lib/active_support/cache/redis_cache_store.rb#L484) and replicating the issue.

**Comment by casperisfine** [comment]
@booleanbetrayal could you remove your error handler just to confirm?

Because I agree with @ghiculescu I don't see how the backtrace you showed could bubble up. (except for the raw `Errno::ETIMEDOUT`, which should be fixed in hiredis).

**Comment by byroot** [comment]
I'll close since I this stage I don't think it's a Rails bug. If you do get further evidence that this is a Rails bug, I'll happily reopen.

**Comment by NicholasAStuart** [comment]
Is there any way to detect the redis timeout/connection error from the caller of `get`, `fetch`, or `write`? I'm running into scenarios where we're experiencing timeouts when calling redis, and these methods return nil. 

The behavior of this being a cache miss instead of (optionally) being a raised error is causing issues downstream. I understand that the code should be built with cache-misses in mind, but there's a fine distinction between cache entry not present and unable to read due to cache connection issues. The latter is something we might want to return to a client or fail more gracefully.

**Comment by casperisfine** [comment]
> Is there any way to detect the redis timeout/connection error from the caller of `get`, `fetch`, or `write`?

No, you'd have to patch the `failsafe` method: https://github.com/rails/rails/blob/c3664b0c2b509fc0a47929f42afbd716959c8f4c/activesupport/lib/active_support/cache/redis_cache_store.rb#L459-L472 (or subclass the adapter to make your own behavior)

**Comment by booleanbetrayal** [comment]
FWIW - We still see request failures when running just the `ruby` driver and not specifying an `error_handler`. Requests just timeout and this causes our K8s liveness probes to fail, bringing the application down. So, while we are currently treating Redis as critical path that cannot undergo downtime, I was definitely hoping this was not the case based on the documentation. I'm sort of left wondering the same question as I had when I opened this issue: what are the failsafe expectations of `RedisCacheStore`?

**Comment by casperisfine** [comment]
It's here: https://github.com/rails/rails/blob/cdd1414f3b5991e2315d58e7bf830efbbcbc0032/activesupport/lib/active_support/cache/redis_cache_store.rb#L461

Any Redis error is swallowed, as simple as that. (If you ask me it should be limited to `Redis::BaseConnectionError`, but whatever).

If your requests are failing from errors coming from the redis client but are not caught by this, then report it to the redis client: https://github.com/redis/redis-rb, I'll happily look at it (I'm the maintainer).

But the backtraces you posted initially are no proof of that.
