### ISSUE TITLE
Horizontal sharding & migration with data changing script

### ISSUE THREAD

**Issue by alpracka** [rails/rails#42873]
Hello folks and @eileencodes 

I was trying the Horizontal sharding and couldn't go through this. Thanks for your job anyway 👍 

### Steps to reproduce
``` shell
git clone https://github.com/alpracka/sharding_migrations
cd sharding_migrations && bundle
bin/rails db:create
bin/rails db:migrate
```

### Expected behavior
Migrations should be finished on all databases.

### Actual behavior
Migration with data changing script is not finished and goes to zombie mode.

Few notes:
- No matter if the script is written like reversible block or def up/down methods.
- PostgreSQL:
It just hangs out like on the gif below.
- SQLite:
It seems to work **but** doesn't work if there are some records in the database. But it seems to be a different issue as `reset_column_information` doesn't work in this case 🤷‍♂️.
- MySQL:
All migrations are finished **but** the data changing script is performed only on the primary database because all Animal records in the primary_shard_one database have nil value of the attribute `lives`.

### System configuration
**Rails version**: 6.1.4 (I also tried the main branch with same results)

**Ruby version**: 3.0.1

![alt text](https://timi.cz/system/sharding_migrations.gif "Demo")

**Comment by eileencodes** [comment]
Your `sharded_record.rb` is set up wrong - since it's primary it shouldn't exist actually. The connection code needs to go in `ApplicationRecord`, that's the "default" connection.

Move this:

```ruby
  connects_to shards: {
    default: { writing: :primary },
    shard_one: { writing: :primary_shard_one }
  }
```

into ApplicationRecord and delete `ShardingRecord`.

**Comment by alpracka** [comment]
I've updated the code into a *guided* branch.

### PostgreSQL

```
$ bin/rails db:migrate
== 20210726081010 CreateAnimals: migrating ====================================
-- create_table(:animals)
   -> 0.0516s
== 20210726081010 CreateAnimals: migrated (0.0518s) ===========================

== 20210726081137 AddLivesToAnimals: migrating ================================
-- add_column(:animals, :lives, :integer)
   -> 0.0030s
== 20210726081137 AddLivesToAnimals: migrated (0.0284s) =======================

rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

connection is closed
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
ActiveRecord::ConnectionNotEstablished: connection is closed
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
PG::ConnectionBad: connection is closed
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
ActiveRecord::ConnectionNotEstablished: connection is closed
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
PG::ConnectionBad: connection is closed
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### SQLite
```
$ bin/rails db:migrate
== 20210726081010 CreateAnimals: migrating ====================================
-- create_table(:animals)
   -> 0.0068s
== 20210726081010 CreateAnimals: migrated (0.0070s) ===========================

== 20210726081137 AddLivesToAnimals: migrating ================================
-- add_column(:animals, :lives, :integer)
   -> 0.0042s
== 20210726081137 AddLivesToAnimals: migrated (0.0409s) =======================

rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

prepare called on a closed database
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
ActiveRecord::ConnectionNotEstablished: prepare called on a closed database
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
ArgumentError: prepare called on a closed database
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
ActiveRecord::ConnectionNotEstablished: prepare called on a closed database
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
ArgumentError: prepare called on a closed database
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

When I remove the data changing script from the `AddLivesToAnimals` migration, there is no issue for PostgreSQL and SQLite.

### MySQL
MySQL works 👍  . It assigns random lives to Animals correctly. I've just hit an issue after the rollback but I can move it to a different issue if you find it useful.

```
$ bin/rails db:migrate
== 20210726081010 CreateAnimals: migrating ====================================
-- create_table(:animals)
   -> 0.0346s
== 20210726081010 CreateAnimals: migrated (0.0347s) ===========================

== 20210726081137 AddLivesToAnimals: migrating ================================
-- add_column(:animals, :lives, :integer)
   -> 0.0561s
== 20210726081137 AddLivesToAnimals: migrated (0.0647s) =======================

== 20210726081010 CreateAnimals: migrating ====================================
-- create_table(:animals)
   -> 0.0999s
== 20210726081010 CreateAnimals: migrated (0.0999s) ===========================

== 20210726081137 AddLivesToAnimals: migrating ================================
-- add_column(:animals, :lives, :integer)
   -> 0.0126s
== 20210726081137 AddLivesToAnimals: migrated (0.0149s) =======================

$ bin/rails db:rollback:primary_shard_one
== 20210726081137 AddLivesToAnimals: reverting ================================
-- remove_column(:animals, :lives, :integer)
   -> 0.0604s
== 20210726081137 AddLivesToAnimals: reverted (0.0634s) =======================

$ bin/rails db:migrate
== 20210726081137 AddLivesToAnimals: migrating ================================
-- add_column(:animals, :lives, :integer)
   -> 0.0133s
== 20210726081137 AddLivesToAnimals: migrated (0.0186s) =======================

rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate entry '20210726081137' for key 'schema_migrations.PRIMARY'
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '20210726081137' for key 'schema_migrations.PRIMARY'
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'

Caused by:
Mysql2::Error: Duplicate entry '20210726081137' for key 'schema_migrations.PRIMARY'
/Users/nikos/Workspace/sharding_migrations/bin/rails:5:in `<top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:10:in `block in <top (required)>'
/Users/nikos/Workspace/sharding_migrations/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by storm2513** [comment]
I faced with same issue, but it's not related to sharding.

I created a demo repo (absolutely new rails app with one `Test` model):
https://github.com/storm2513/rails-connects-to-issue

If I add [`connects_to database: { writing: :primary }` in `ApplicationRecord` and try to use `Test` in migration](https://github.com/storm2513/rails-connects-to-issue/commit/35848d60038df08422507aa00f41aee9c3c2d42f) it fails with same errors as above.

Demo for [SQLite](https://github.com/storm2513/rails-connects-to-issue) and [PostgreSQL](https://github.com/storm2513/rails-connects-to-issue/tree/postgresql)

**Comment by eileencodes** [comment]
> I faced with same issue, but it's not related to sharding.

Thanks for the update, I was aware of that which is why I didn't immediately re-open this issue (I think there's another issue elsewhere that's more accurate but I don't know where it is offhand). Unfortunately I've been trying off and on to fix this for a few months and haven't found a good solution yet.

**Comment by alpracka** [comment]
I've tested with the latest stable + the main branch and the problem remains (testing only Postgresql now).

**Comment by eileencodes** [comment]
As noted on the PR, I did not backport to any of the stable branches because the change to fix is too significant so we should only be testing against `main`

As far as I can tell there is still an issue but it's a different issue where the shard ends up hanging and not raising an error. I made my own demo because the original is based on an old version of Rails and the connection models aren't set up correctly. If you are seeing an error instead of hanging on `main` please provide an updated demo. 

I'll reopen but I don't know when I'll be able to spend time debugging this. In the meantime I'd recommend adding a column in one migration and in a followup migration running the data transition code.

**Comment by alpracka** [comment]
@eileencodes Aah sorry, my fault, I forgot to test it at the `guided` branch as you pointed out. I've updated and tried it and It is okay 👍

And your workaround works in my original `master` branch too. However, you said it is misconfigured. What I'm trying to achieve is that only some models are sharded. E.g. there is a primary model Profile that has many :projects and many :tasks. Profiles are kept in the primary database but Projects & Tasks are kept in a separate database that belongs to a profile in fact. So from the users' view:

```
Profile ID 1 can have Project with ID 1 and Task with ID 1
Profile ID 2 can have Project with ID 1 and Task with ID 1
Profile ID 2 can not exist - unique ID DB error.
```
And it works so far 😊
