### ISSUE TITLE
API documentation for < 7.0 links broken

### ISSUE THREAD

**Issue by mobilutz** [rails/rails#44042]
I copied this over from the rails discussion board to here:
https://discuss.rubyonrails.org/t/api-documentation-broken-for-7-0-0-versions/79574

### Steps to reproduce
* Go to Ruby on Rails API e.g. of 6.1.4: https://api.rubyonrails.org/v6.1.4/
* click on any element in the left sidebar e.g. `AbstractController`
* one is being redirected to this 404 URL: https://edgeapi.rubyonrails.org/undefinedclasses/AbstractController.html

### Expected behavior
Correct documentation page being displayed:
https://api.rubyonrails.org/v6.1.4/classes/AbstractController.html

### Actual behavior
Redirect to the wrong URL which is also a 404 page:
https://edgeapi.rubyonrails.org/undefinedclasses/AbstractController.html

### System configuration
**Rails version**: N/A

**Ruby version**: N/A

**Comment by fxn** [comment]
I believe we have two issues with 6.1 docs:

1. Some were not properly generated due to missing system dependencies or Bundler conflicts.
2. In the one I have been able to generate manually as a quick fix, the links in the sidebar do not preserve the prefix. For instance, if you go to https://api.rubyonrails.org/v6.1/ and click on anything in the sidebar, you'll see the main panel is showing 7.0 docs, that is what you'd get without the path prefix.

I believe we should fix (2) first, and then regenerate 6.1 and 7.0 documentation.

@p8 (2) seems to be happening to all 6.1.x docs and it went unnoticed because they were not using the path prefixes like `/v6.1`. Could it be related to the SDoc upgrade that replaced frames?

/cc @zzak

**Comment by fxn** [comment]
As a quick fix, we could also manually downgrade SDoc for all 6.1 and regenerate with frames, since people do not have documentation.

@p8 @zzak I'll leave that to your preference.

**Comment by p8** [comment]
Thanks @fxn !
I’ll have a look tomorrow.

**Comment by zzak** [comment]
Thanks @p8 for looking into this :bow:

**Comment by p8** [comment]
https://github.com/zzak/sdoc/pull/176 should fix this.

**Comment by fxn** [comment]
I have regenerate the APIs for all `v6.1.[0-4]`, and the one linked to `v6.1` (`v6.1.4.4`).

**Comment by rafaelfranca** [comment]
Thanks!

**Comment by fxn** [comment]
And now all `v6.1.x.y`.

**Comment by dmke** [comment]
This issue solves only half of #43955. As written there, this still won't work:

> 1. Visit https://api.rubyonrails.org/v6.1/
> 2. In the main content area, click on the "Active Record" link in the second section:
>   
>   ![image](https://user-images.githubusercontent.com/327411/146944859-b85365e8-2b45-4a12-8e6b-10a5271f890e.png)
>
> 3. I'm redirected to `https://edgeapi.rubyonrails.org/activerecord/README_rdoc.html`, which answers with a 404 error.

The generated link seems to be wrong, and should be pointing to `./files/activerecord/README_rdoc.html`, not `../activerecord/README_rdoc.html`:

![image](https://user-images.githubusercontent.com/327411/148355180-0474e5f9-a668-465e-90af-327f7f5cf1f4.png)

N.B.: On https://api.rubyonrails.org, the same link points to `../../files/activerecord/README_rdoc.html`, so there's still something wrong with generating relative URLs.

**Comment by p8** [comment]
Thanks @fxn!
@dmke I'll have a look if I can fix those links.
