### ISSUE TITLE
[ActionText] Editor didn't load attachments after saving and opening edit again.

### ISSUE THREAD

**Issue by joaovictor-local** [rails/rails#52233]
Hi! I am expecting this strange bug on fresh new rails application I hope someone could help me.

### Steps to reproduce
1. `rails new my-blog -d postgresql`.
2. `rails action_text:install`
3. `rails g scaffold Post name:string title:string content:text`
4.  Adds tag at Model

```ruby
class Post < ApplicationRecord
    has_rich_text :content
end
```

5. Add tag at _form
```ruby
<%= form_with(model: post) do |form| %>
  ...
  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>
  ...
<% end %>
```
6. Test it
https://github.com/rails/rails/assets/63271570/0a142613-8010-41d3-bb65-a44228437076

### Expected behavior
It used render the edit after save just in the past (1 year ago at least)

### Actual behavior
It didn't render the attachments thumbs and not even the label for .zips for example.

### System configuration
**Rails version**: Rails 7.1.3.4

**Ruby version**: ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux]

**Comment by p8** [comment]
@joaovictor-local This should be fixed on the stable-7-1 branch. See https://github.com/rails/rails/issues/52127 and https://github.com/rails/rails/pull/52093.
@rafaelfranca could we get a 7.1.3.5 release to fix this in an offical release?

**Comment by jagthedrummer** [comment]
I was just coming to file an issue with the same repro steps. Would be really nice to get a bug fix release out asap.

**Comment by jagthedrummer** [comment]
I'm not entirely sure that the change from #52093 fixes this.

I added this initializer to a brand new rails app:

```ruby
# config/initializers/action_text_bug_fix.rb

require "action_text/content"

module ActionText
  class Content
    def render_attachments(**options, &block)
      puts "*" * 300
      puts "calling monkey patched render_attachments"
      puts "*" * 300
      content = fragment.replace(ActionText::Attachment.tag_name) do |node|
        if node.key? "content"
          node["content"] = sanitize_content_attachment(node["content"])
        end
        block.call(attachment_for_node(node, **options))
      end
      self.class.new(content, canonicalize: false)
    end
  end
end
```

I've verified that my monkey patched version of `render_attachments` is being called when I visit the edit page, but the image still isn't showing up in the editor.

It looks like there's just no `img` tag included in the generated markup on the edit page:

![CleanShot 2024-07-05 at 11 03 26](https://github.com/rails/rails/assets/58702/4f631d97-1fe0-4e4c-a392-0d5f3dbe8de3)

On the show page there is an `img` tag inside the `figure` element:

![CleanShot 2024-07-05 at 11 04 43](https://github.com/rails/rails/assets/58702/d35ba3de-7cd1-458c-b5f5-a9ba6a3811ac)

**Comment by jagthedrummer** [comment]
I've also experimented with a few different unreleased versions via `github:` installation. And none of them seem to fix the problem.

### `branch: "7-1-stable"`

```
gem "rails", github: "rails/rails", branch: "7-1-stable"
```

In `7-1-stable` the images are now broken on the `index` and `show` pages, and are still completely missing on the `edit` page.


![CleanShot 2024-07-05 at 11 50 35](https://github.com/rails/rails/assets/58702/2d8f7fe7-7135-483d-a875-4da28b632920)

### `branch: "7-2-stable"`

```
gem "rails", github: "rails/rails", branch: "7-2-stable"
```

In `7-2-stable` the images work as expected on the `index` and `show` pages, but are still completely missing on the `edit` page.

### `branch: "main"`

```
gem "rails", github: "rails/rails", branch: "main"
```

In `main` (which gets me `8.0.0.alpha`) the images work as expected on the `index` and `show` pages, but are still completely missing on the `edit` page.

**Comment by jagthedrummer** [comment]
I was able to get things working with this modified monkey patch. The problem is that the fix in #52093 only checks whether the `content` **key** is _present_, but it doesn't check whether that key has a non-empty **value**. When the key is there with an empty value we should strip it out.

```ruby
# config/initializers/action_text_bug_fix.rb

require "action_text/content"

module ActionText
  class Content
    def render_attachments(**options, &block)
      content = fragment.replace(ActionText::Attachment.tag_name) do |node|
        if node.key?("content") && node["content"].present?
          node["content"] = sanitize_content_attachment(node["content"])
        elsif node.key?("content")
          node.remove_attribute("content")
        end
        block.call(attachment_for_node(node, **options))
      end
      self.class.new(content, canonicalize: false)
    end
  end
end
```

**Comment by marvinick** [comment]
> I was able to get things working with this modified monkey patch. The problem is that the fix in #52093 only checks whether the `content` **key** is _present_, but it doesn't check whether that key has a non-empty **value**. When the key is there with an empty value we should strip it out.
> 
> ```ruby
> # config/initializers/action_text_bug_fix.rb
> 
> require "action_text/content"
> 
> module ActionText
>   class Content
>     def render_attachments(**options, &block)
>       content = fragment.replace(ActionText::Attachment.tag_name) do |node|
>         if node.key?("content") && node["content"].present?
>           node["content"] = sanitize_content_attachment(node["content"])
>         elsif node.key?("content")
>           node.remove_attribute("content")
>         end
>         block.call(attachment_for_node(node, **options))
>       end
>       self.class.new(content, canonicalize: false)
>     end
>   end
> end
> ```

This works, tyvm!

**Comment by swanson** [comment]
@jagthedrummer I'm wondering if the fix is not working because invalid blank `content` values were creating during the window when you were running 7.1.3.4? The 7-1 stable branch seems to work for us but we explicitly cleaned up the "bad data" caused by the original sanitizer issue: https://github.com/rails/rails/issues/52127#issuecomment-2216256859

**Comment by jagthedrummer** [comment]
@swanson I don't _think_ that's the case, I'm pretty sure that I was creating new records each time I tried a new branch. But I wouldn't swear to it since it's been a month and a half since I did the tests.
